### ISSUE TITLE
No data was found with this identifier

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#101]
I tried to get the labels to a new statistical product, naio_18_agg_60_r2

I got the message "No data was found with this identifier." 

My questions are two-fold:
How does labelling go, from a non-programmatic point of view?
Can the package give in this rare case a more helpful error message (i.e. write to xy@z to request metadata, report the problem, etc.)

**Comment by jhuovari** [comment]
Could you share your code for labelling? I did not have a problem labelling that table. 

Labels for codes are get from Eurostat dictionaries.

**Comment by antaldaniel** [comment]
Apologies, something went wrong in the loop, I could re-label it. But curious how I got that error message and how it could improve.  And a very off topic: how could I bring in the main branch to rOpenGov of iotables?

**Comment by jhuovari** [comment]
I don't know of the error message, as it is not from the eurostat-package. I you enconter it again, please let us know. 

iotables looks nice and I would like to see it as a part of rOpenGov. I guess you could contanct @antagomir.

**Comment by antagomir** [comment]
Yes, thanks for the report & new packages are also welcome. I also could not find this error msg from eurostat package. If this occurs again, can you send the exact reproducible example and we can see if something could be improved. In general, it would indeed be good to have more informative error messages. We will consider this.

**Comment by antaldaniel** [comment]
Yes, sorry about the lack of reproducible issue. I heavily use the eurostat package, and it only occurred once, and I cannot reproduce it.
