### ISSUE TITLE
Invalid column specification

### ISSUE THREAD

**Issue by mhaber** [rOpenGov/eurostat#102]
I get an 'Invalid column specification' error when I'm trying to use get_eurostat on this dataset: [ilc_scp05](http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=ilc_scp05&lang=en)

`get_eurostat("ilc_scp05")`

> trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Filc_scp05.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 126542 bytes (123 KB)
downloaded 123 KB
Error: Invalid column specification

Setting the filters argument to return only parts of the dataset results in a 'Status code: 416' error.

**Comment by jhuovari** [comment]
What version you are using? For me it works fine. You can also try it again, as it might be a temporary eurostat problem.

**Comment by mhaber** [comment]
I was using the development version from Github. You are correct, it seems to work fine with official release. Thanks for the quick reply.

**Comment by antagomir** [comment]
Good to know it works with the official version. But I guess we also should try to make sure it works with devel version.

**Comment by jhuovari** [comment]
For me it works also with the latest devel version. Did you have some previous version?
