### ISSUE TITLE
keepflags not keeping flags

### ISSUE THREAD

**Issue by GitHubFriendly** [rOpenGov/eurostat#104]
I try to get data froom Eurostat and want to include the flags in the dataset. I try to use the "keepFlags" but it doesnt give me any flags. I would be very thankful if someone can help me!

An example.

The input:
get_eurostat("demo_gind", filters = list("geo"='PL', "indic_de"=c('JAN'), sinceTimePeriod="2005"), time_format = "raw", stringsAsFactors = TRUE, keepFlags = TRUE)

Gives the result:
# A tibble: 13 × 4
   indic_de    geo   time   values
     <fctr> <fctr> <fctr>    <int>
1       JAN     PL   2005 38173835
2       JAN     PL   2006 38157055
3       JAN     PL   2007 38125479
4       JAN     PL   2008 38115641
5       JAN     PL   2009 38135876
6       JAN     PL   2010 38022869
7       JAN     PL   2011 38062718
8       JAN     PL   2012 38063792
9       JAN     PL   2013 38062535
10      JAN     PL   2014 38017856
11      JAN     PL   2015 38005614
12      JAN     PL   2016 37967209
13      JAN     PL   2017 37972964

I would expect a sixth column with the flagdata, or am I misunderstanding something? (I know that the value for 2010 has a flag about broken time-series in the EUROSTAT-database)

**Comment by jhuovari** [comment]
The eurostat api data does not include flags, so you can not use `filter` argument with `keepFlags`. So get first data without filter and filter it yourself later.

This should be documented and warning added.

**Comment by GitHubFriendly** [comment]
Thank you, it works fine without filters!
