### ISSUE TITLE
Uses up to 4GB of memory to load sts_inpr_m

### ISSUE THREAD

**Issue by beberking** [rOpenGov/eurostat#106]
Dear author,

Trying to download and use the sts_inpr_m database from Eurostat uses up to 4GB of memory. For a 300MB database, this definitely to much.

It leads to failure (error: cannot allocate vector of size ...), almost allways on 32bits R, and often on 64bits R with 8GB of memory.

The issue seems to come from tidyr::gather_, of which I know you are not in charge, but it renders your package unusable to load the sts_inpr_m database.

Best regards,
Bertrand

**Comment by jhuovari** [comment]
Could you try this with a development version?:
```
devtools::install_github("ropengov/eurostat")

```

I don't get any errors and object size of the output is 270.4 Mb.

**Comment by antagomir** [comment]
I am closing for now. Let us reopen if the problem persists with the devel version after testing.
