### ISSUE TITLE
CRAN pdf vignette

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#107]
.. was reported to be broken. Make an update to CRAN as soon as the time allows. Were new features in the pipeline still, to be included in that update?

**Comment by pbiecek** [comment]
In 2275dea  I've corrected eurostat_tutorial.Rmd (it was not working for me) and renamed README.Rmd to md in 2017_RJournal_manuscript (otherwise there as a vignette WITHOUT TITLE).
IMHO it's ready to go to CRAN

**Comment by antagomir** [comment]
Tnx! Something in travis went broken, I am planning to have a look. When all ok, I can submit to CRAN.
