### ISSUE TITLE
DS-645593 does not exist or is not readable

### ISSUE THREAD

**Issue by fgriffon** [rOpenGov/eurostat#110]
Hello,

Great package! I have however an issue. I tried to reach the EU trade database ("EU trade since 1988 by HS2,4,6 and CN8") but got an error message in return.

```
> query <- search_eurostat("EU trade since 1988")
> dim(query)
[1] 1 8
> query$code[1]
[1] "DS-645593"
> dat <- get_eurostat(query$code[1])
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2FDS-645593.tsv.gz'
downloaded 17 KB

Error in get_eurostat_raw(id) : 
  DS-645593 does not exist or is not readable
```

Is this database not accessible through this package?
Thanks in advance for your answer

**Comment by antagomir** [comment]
A quick browsing of this dataset in [eurostat portal](http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=DS-645593&lang=en) suggests that all values are empty. I did not browse through all options, though. This could be a possible reason if there is no actual data. Adding an informative warning/error could be useful, for instance URL to the data with a suggestion that the values might be empty. First let us ensure, however, that this data item is indeed empty.

**Comment by fgriffon** [comment]
Hi, thanks for the reply!

I use this database quite often for my job and there are plenty of trade data in there.

The eurostat portal link you put in your message may give some indications on what could be the problem. The data table is empty because the product code selected is "00" (refering to the category "Total for countries whose data are confidential, broken down by origin and/or destination", which is a weird HS code). If you try other products code, it works. Also that the last updated data are for March 2018 at best and February 2018 for sure.

I tried using the get_eurostat function with filters.

```
query <- search_eurostat("EU trade since 1988")
id <- query$code[1]
fi <- list(Product="07", Period=c("201752"))
dat <- get_eurostat(id, filters=fi)
```
but got this error message:
```
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  Failure to get data. Probably invalid dataset id. Status code: 400
```

The filters names I used here come from the header of csv file you get if you download manually data on this portal. Here are the headers name in order: "Period", "Reporter", "Partner", "Product", "Flow", "Indicators", "Value" and "Flag and footnotes". Does not seem to work. Do you have an idea of the filter names we should use?

**Comment by jhuovari** [comment]
That is part of Prodcom data and I don't think it is included in Eurostat bulk download facility or json api. At least, not same way as other data. From where did you downloaded the csv manually?

**Comment by fgriffon** [comment]
> From where did you downloaded the csv manually?

You can use the portal link Antagomir provided in his last message. Using this portal, you can change the parameters (product, reporters, partners, etc) clicking on the "+" nearby each parameter (a window will open where you can change the value of the paramater). When you are done with your selection, you go on the top panel where you can click on a download option.

Otherwise, you go to this link[http://ec.europa.eu/eurostat/data/database?p_p_id=NavTreeportletprod_WAR_NavTreeportletprod_INSTANCE_nPqeVbPXRmWQ&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_pos=1&p_p_col_count=2](url). The path to find DS-645593 database the  is "database by themes"/"international trade"/"international trade in goods"/""international trade in goods - detailed data". Clicking on the DS-645593 lign will open the database in a new window.

> That is part of Prodcom data and I don't think it is included in Eurostat bulk download facility or json api

Do you think there is still a chance to extract the data using R anyway? Thanks for your help

**Comment by jhuovari** [comment]
Based on the [metadata](http://ec.europa.eu/eurostat/cache/metadata/en/ext_go_agg_esms.htm), data can be found also in the bulk download facility, but under comext folder: [http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&dir=comext](http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&dir=comext).

It is unfortunately distributed differently than other eurostat data. Seems like monthly updates can be found as 7z-files. So currently eurostat-package can't get that data. 

It do have also its own comext database: [http://epp.eurostat.ec.europa.eu/newxtweb/](http://epp.eurostat.ec.europa.eu/newxtweb/), but I didn't quickly find any info on possible API.
There is also annual data as [excel-files](http://ec.europa.eu/eurostat/web/prodcom/data/excel-files-nace-rev.2).

**Comment by antagomir** [comment]
Ok - one problem here is that the search (`get_eurostat`) is performed with an ID that is returned by `search_eurostat` of the same package. It would be reasonable to assume that `search_eurostat` is only returning valid IDs that lead to a successful search. We could investigate if there are workarounds. 

Moreover, adding download utilities for the other above mentioned data sources from eurostat should be considered as well.

**Comment by jhuovari** [comment]
I agree. It seems that the `search_eurostat()` returs NAs for DS- tables in update, data end and data start columns. So, we could use that information on `search_eurostat()`.  Probably warning would be enough, as we do not know for sure if that is a general rule?

A method to get those data would be really great to have. Would require some investigation, and work.

**Comment by antagomir** [comment]
Informative error message is now provided.

**Comment by razvanvilceanu** [comment]
Hi, I am trying to get this data using a python package and it does not work due to the same reasons mentioned above. Is this fixed for R at this moment?

**Comment by antagomir** [comment]
No progress since the last discussion - the eurostat API will be updated in November, probably need to be considered as part of those updates.
