### ISSUE TITLE
Hard dependency on dplyr makes lag unusable with time series

### ISSUE THREAD

**Issue by beberking** [rOpenGov/eurostat#111]
Dear eurostat author,

The new hard dependency on dplyr forces R to load the whole dplyr package in the user namespace. This results in overriding stats::lag with dplyr::lag, which is not compatible with time series. So it is not possible to load data from eurostat with your package and then include it in econometric formula with lags.

Could you please revert this dependency to a Imports?

Best regards,
Bertrand

**Comment by jhuovari** [comment]
Thanks for notifying us. I think we should definitely do that.
