### ISSUE TITLE
NUTS 2006 in get_eurostat_geospatial

### ISSUE THREAD

**Issue by muuankarski** [rOpenGov/eurostat#112]
> I am wondering if it's possible to use the NUTS 2006 geospatial file within get_eurostat_geospatial. The reason I ask is that I am trying to map some statistics from earlier years, based on NUTS 2006.

**Comment by muuankarski** [comment]
NUTS releases 2003, 2006, 2010 and 2013 are now all available with `get_eurostat_geodata()` using new `year` argument with https://github.com/rOpenGov/eurostat/commit/84f34abd923efb8fb1b5b29bfbbb95194b8d06b3

An example at country level:

```r
library(dplyr)
library(sf)
l013 <- eurostat::get_eurostat_geospatial(resolution = 20, nuts_level = "0", output_class = "sf", year = 2013) %>% 
  mutate(year = 2013)
l010 <- eurostat::get_eurostat_geospatial(resolution = 20, nuts_level = "0", output_class = "sf", year = 2010) %>% 
  mutate(year = 2010)
l006 <- eurostat::get_eurostat_geospatial(resolution = 20, nuts_level = "0", output_class = "sf", year = 2006) %>% 
  mutate(year = 2006)
l003 <- eurostat::get_eurostat_geospatial(resolution = 20, nuts_level = "0", output_class = "sf", year = 2003) %>% 
  mutate(year = 2003)

dat <- rbind(l013,l010,l006,l003)

# devtools::install_github("tidyverse/ggplot2")
library(ggplot2)
ggplot(dat) +
  geom_sf(aes(fill = geo)) + facet_wrap(~year) +
  theme_light() + theme(legend.position="none") +
  coord_sf(xlim=c(-12,44), ylim=c(35,70))
```

![plot](https://user-images.githubusercontent.com/1525240/40886857-07d9e554-6748-11e8-9293-a7d3460d7626.png)

**Comment by muuankarski** [comment]
Apologies for delay, the path to GISCO api had been changed. Fixed with https://github.com/rOpenGov/eurostat/commit/ee93dfe5262a2daef545d9cf7cae71ce134b1a30 - please install the latest from Github and test!

**Comment by mschnetzer** [comment]
Works great now, thanks a lot!!
