### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#113]
I am testing an upgrade (and long missing documentation) to the rOpenGov/iotables package that builds upon eurostat. 

> The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .

On Travis I get the above problem, eurostat does not install on 

> Build system information
> Build language: r
> Build group: stable
> Build dist: trusty
> Build id: 389207332
> Job id: 389207333
> Runtime kernel version: 4.14.12-041412-generic
> travis-build version: 23b9e15b3
> Build image provisioning date and time
> Tue Dec  5 20:11:19 UTC 2017
> Operating System Details
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.5 LTS
> Release:	14.04

Did you have similar experience? What may be the cause?   The problem does not persist on Windows 10 or Mac OS, with either old or release version of R.

**Comment by antagomir** [comment]
This is strange. We recently had problems with multiple new gis-related dependencies but now all travis builds go through successfully. Does the problem still persist? It could be that some of the new external dependencies are too new for Trusty. Is it mandatory to get this running on Trusty, or could that be omitted? Already >4 years old.

**Comment by antaldaniel** [comment]
This problem persists, and now already on OSX, too with trusty, without trusty on Linux only. 

Skipping install of 'tidyr' from a cran remote, the SHA1 (0.8.1) has not changed since last install.
  Use `force = TRUE` to force installation
missing: eurostat
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .

Can you probably suggest me a command to manually add the package? I already removed from my travis.yml the cache option, but the problem is the same.

**Comment by antagomir** [comment]
Sorry for delays. Does devtools::install_github("ropengov/eurostat") not work?
