### ISSUE TITLE
Download monthly data from Eurostat with eurostat package

### ISSUE THREAD

**Issue by mattiadisalvo** [rOpenGov/eurostat#114]
Hi all,

I am trying to download asylum monthly applications from Eurostat using the eurostat package. I would like to get only the latest figures, preferably the latest month available or all 2018 months would work too. The problem is that downloading the entire dataset crashes Rstudio, while I get an error when filtering with sinceTimePeriod (see code below).

Hope someone knows a way around this.

Thanks,
Mattia

# downloading the entire dataset crashes Rstudio
applications_all <- get_eurostat("migr_asyappctzm", time_format = "raw")

applications_latest <-subset(applications_all,   time == 2018)

# filtering with sinceTimePeriod returns error **“Failure to get data. Status code: 416. Some datasets are not accessible via the eurostat interface.”**
applications <-get_eurostat("migr_asyappctzm",  filters = list(sinceTimePeriod = 2018), type = "label", time_format = "num")

**Comment by jhuovari** [comment]
The data is monthly and you are using raw-format, so to get the latest you should have:
```
applications_latest <-subset(applications_all, time == "2018M03")
```
But it should not crash, and it does not crash for me. Be sure to use the up-to-date version. Or even the github-versio. Let us no if it still crashes.

The problem with the second one is that it contains too much data for api-call. Allowed amount of data by eurostat on one call is rather limited. For example this should work:
```
applications <-get_eurostat("migr_asyappctzm", filters = list(sinceTimePeriod = 2018,
                                                              citizen = "AF",
                                                              sex = "T",
                                                              age = "TOTAL",
                                                              geo = "AT"), 
                                              type = "label", time_format = "num")
```

**Comment by mattiadisalvo** [comment]
Hi Janne,

Thank you very much for your help. Indeed, tailoring down the selection to one country of origin allowed me to download just the last month (using lastTimePeriod = 1 instead of sinceTimePeriod = 2018). I will then run separate scripts for group of countries I am interested in. 

Nevertheless, when I download the entire dataset Rstudio (as well as my PC) still crashes, but I believe it is just a matter of file size, and, anyway, I do not care to download all past data.

**Comment by antagomir** [comment]
I am wondering if there is a way to detect if the query size exceeds eurostat limits so that we could avoid function failure, add informative warning, and return NULL. We can leave this issue open but something to keep in mind.

**Comment by jhuovari** [comment]
The error message is based on returned status code. But, I have not found any explanation for eurostat specific codes. And I do think, that the code for this case have changed from 500 to, it seems, to 416. At the present, there are different messages for codes 400, 500 and others.
