### ISSUE TITLE
Problem with waste composition data

### ISSUE THREAD

**Issue by Maklawe** [rOpenGov/eurostat#115]
I am searching waste data and I found that R package “Eurostat” is very useful and intuitive to use. I will like to thank you for providing this unique tool. I am looking for dataset on composition of municipal solid waste for EU countries. 
I used the following code:
 
library(eurostat)
library(rvest)
library(tidyverse)
library(countrycode)
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dat2=#name of the data frame
  search_eurostat("Composition of municipal waste", 
                  type = "dataset")[1,"code"]%>% #export data labelled 
   get_eurostat(time_format = "num")%>%# get the dataset
  mutate(Country_name=add_column(countrycode(geo, "iso2c", "country.name")))#
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#convert country code with country name
dat2%>%View()

The problem is that I am getting the data only for Palestinian Territories, Egypt, Lebanon, Tunisia, Algeria, Israel, Syria and Morocco. There is no data for the EU countries. I am wondering if there is another specific id for EU countries?
I will appreciate any help you will provide. 
Vincent

**Comment by jhuovari** [comment]
The dataset is from Non EU part of the database. You can use `search_eurostat("waste", type = "dataset")` or the eurostat web page for a search EU data.
