### ISSUE TITLE
get_eurostat timeout

### ISSUE THREAD

**Issue by mwilkens1** [rOpenGov/eurostat#118]
Hi I am getting a timed out connection when I apply filters when using get_eurostat:

> estat_raw2 <- get_eurostat("gov_10a_exp", filters = list(geo = "FI"))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to ec.europa.eu port 80: Timed out

It works fine when not using filters so I am downloading the full table now and then filter later as a workaround. The table is very big, so it would be nice if I could filter the request. 

Do you know what could be the problem?

**Comment by jhuovari** [comment]
The data is too big with just geo -filter. The eurostat api accepts only very limited datasets.
This should work:
```
estat_raw2 <- get_eurostat("gov_10a_exp", 
                           filters = list(geo = "FI",
                                          sector = "S13",
                                          cofog99 = "GF01",
                                          na_item = "D1"))
```

**Comment by mwilkens1** [comment]
Thanks for your reply but sorry, I am getting the same results

> estat_raw <- get_eurostat("gov_10a_exp", filters= list(geo="FI",sector="S13",cofog="GF01",na.item="D1"))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to ec.europa.eu port 80: Timed out

I don't think its too big, because getting the full dataset is no problem at all, other than that it takes time which is the reason why I would like to filter

> estat_raw <- get_eurostat("gov_10a_exp")
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fgov_10a_exp.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 16041495 bytes (15.3 MB)
downloaded 15.3 MB

|==============================================================================================================================================================| 100%  208 MB
Table gov_10a_exp cached at C:\Users\mwi\AppData\Local\Temp\RtmpIdK0Om/eurostat/gov_10a_exp_date_code_TF.rds
Warning message:
package ‘bindrcpp’ was built under R version 3.4.3

**Comment by jhuovari** [comment]
You have wrong filter names. Use cofog99 and na_item.

The full download is different from the download with filters. With filters the amount of data is limited. See `help(get_eurostat)`

**Comment by mwilkens1** [comment]
You are right that was a typo sorry about that

copy pasted your code, but the problem persists

> estat_raw2 <- get_eurostat("gov_10a_exp", 
+                            filters = list(geo = "FI",
+                                           sector = "S13",
+                                           cofog99 = "GF01",
+                                           na_item = "D1"))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to ec.europa.eu port 80: Timed out

**Comment by jhuovari** [comment]
OK. Then it could be proxy problem. See solution from #99. I might work.

**Comment by mwilkens1** [comment]
That's it, thanks very much for your swift replies! Much appreciated
