### ISSUE TITLE
I was trying to get geocode, but got this timeout issue. Can anyone help solve this? Thanks!

### ISSUE THREAD

**Issue by fananan** [rOpenGov/eurostat#121]
> library(httr)
Warning message:
package ‘httr’ was built under R version 3.3.3 
> library(rjson)
> data <- paste0("[",paste(paste0("\"",saf_addr$address,"\""),collapse=","),"]")
> url  <- "http://www.datasciencetoolkit.org/street2coordinates"
> response <- POST(url,body=data)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by fananan** [comment]
It works on my own macbook, but when I tried it on my work computer, it failed. Is that possible that my work computer blocks the connection?

**Comment by jhuovari** [comment]
It is probably a proxy issue. See details of the help(get_eurostat_json) to connect true proxy.
