### ISSUE TITLE
Eurostat forces the use of https

### ISSUE THREAD

**Issue by paulrougieux** [rOpenGov/eurostat#123]
Eurostat now forces the use of https. This breaks the `get_eurostat()` function. 
Changing the value returned by `eurostat_url()`  to the following: "https://ec.europa.eu/eurostat/" fixes the issue. I suggested a change in a [pull request](https://github.com/rOpenGov/eurostat/pull/122).

**Comment by paulrougieux** [comment]
A more flexible alternative would be to make this `eurostat_url` an option. 
An option can be set at package start-up with:

    options(eurostat_url = "https://ec.europa.eu/eurostat/")

and obtained with: 

    getOption("eurostat_url")
    [1] "https://ec.europa.eu/eurostat/"

**Comment by antagomir** [comment]
I like the latter option ("options"). Could you PR that one?

**Comment by jhuovari** [comment]
Great! I think we should update to CRAN soon as possible. 

Are there any other use cases for option than the eurostat changing the url? Well, this is the second time in a history of the package, if I remember correctly.

**Comment by paulrougieux** [comment]
Probably no other use case, unless someone decides to make a mirror of the Eurostat data with modified datasets. 
I'll make the option change.

**Comment by paulrougieux** [comment]
Fixed in https://github.com/rOpenGov/eurostat/pull/124
