### ISSUE TITLE
R (≥ 3.4.0) ?

### ISSUE THREAD

**Issue by moodymudskipper** [rOpenGov/eurostat#126]
Is your package really using R's latest features consistently ?

I'm stuck with R 3.1 at work and I would greatly appreciate if I could use your package, maybe with an explicit error whenever I try to use a functionality that requires a more recent R.

I know also that some package authors set the requirements to the latest version by default not to bother with extensive testing and thought if it's your case it might be quite safe to set it back to 3.1 or even further. 

I know how to build it myself and change the description file and will probably do this, but it might help others that are in my case.

Thanks for the great work.

**Comment by antagomir** [comment]
In  fact the pkg might work well with some older versions too. I haven't tested. So you would need 3.1.0?

**Comment by moodymudskipper** [comment]
Yes that would be great! thanks
