### ISSUE TITLE
get_eurostat_geospatial() *still* fails to download data 

### ISSUE THREAD

**Issue by hcb101** [rOpenGov/eurostat#127]
In trying to access Eurostat data on 6th November 2018, I have the same issue as @jschoeley had 13 days ago (23/10): get_eurostat_geospatial() fails to download geodata from the Eurostat server and returns a 404 error

> get_eurostat_geospatial(output_class = "sf", resolution = "10", nuts_level = 3)

COPYRIGHT NOTICE

When data downloaded from this page 
<http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units>
is used in any printed or electronic publication, 
in addition to any other provisions 
applicable to the whole Eurostat website, 
data source will have to be acknowledged 
in the legend of the map and 
in the introductory page of the publication 
with the following copyright notice:

- EN: (C) EuroGeographics for the administrative boundaries
- FR: (C) EuroGeographics pour les limites administratives
- DE: (C) EuroGeographics bezuglich der Verwaltungsgrenzen

For publications in languages other than 
English, French or German, 
the translation of the copyright notice 
in the language of the publication shall be used.

If you intend to use the data commercially, 
please contact EuroGeographics for 
information regarding their licence agreements.
          
Cannot open data source <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /site5/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_10M_2013_4258_LEVL_3.geojson was not found on this server.</p>
</body></html>

I see that in his case, the issue was spontaneously resolved but can anyone offer insight as to why it's happened again?

Many thanks,
 Helen

**Comment by rhrzic** [comment]
I am experiencing the same issue. It seems that currently (9 November), the 4258 projection files are not available on the Eurostat server. 
If you look at the release notes, they state that as of 17 September, the 4258 projection has been removed and 4326 recommended ([Source](https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/nuts-2016-release-notes.txt)).

**Comment by hcb101** [comment]
Thank you. I'm sorry but as the projection is not an argument of the command 'get_eurostat_geospatial', how should I address this?

**Comment by rhrzic** [comment]
If you need a very quick workaround, you can manually extract and modify the code that the original function uses ([here](https://github.com/rOpenGov/eurostat/blob/master/R/get_eurostat_geospatial.R)). Here is what I used:

require(httr)
resp <- GET("http://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_",resolution,"M_",year,"_4326_LEVL_2.geojson")
shp <- st_read(content(resp, as="text"), stringsAsFactors = FALSE, quiet = TRUE)

Note that you need to replace the ",resolution," part of the URL with the resolution you want, ",year," with the year you want and LEVL_2 with the NUTS level you want. shp then is the sf dataframe that you can use.

I hope this helps you get started until a formal fix is implemented.

**Comment by hcb101** [comment]
That's perfect, thanks so much for sharing

**Comment by antagomir** [comment]
We should have a look if this requires updates on pkg functions. This might take some time, PRs are welcome meanwhile.

**Comment by antagomir** [comment]
In fact now CRAN checks fail and we have received a request to update the package (otherwise it will be removed from CRAN). The vignette example chunk maps1-1 fails with [get_eurostat_geospatial](https://github.com/rOpenGov/eurostat/blob/master/R/get_eurostat_geospatial.R), and in this case the problematic row in that function is 155. @muuankarski do you have any suggestions how to solve? It seems that something has changed in the data locations.

**Comment by antagomir** [comment]
We were given time till Nov 25 to fix this, or I can ask for extension.

**Comment by jschoeley** [comment]
It seems that you only need to change the requested projection from 4258 to 4326 in the GET() call as files in 4258 projection are not provided anymore.

**Comment by muuankarski** [comment]
Thanks for reopening this, should be fixed in devel now. Please 

- install with `devtools::install_github("ropengov/eurostat", ref = "devel")`
-restart R
-test with `eurostat::get_eurostat_geospatial(resolution = 60, nuts_level = "all", output_class = "sf", year = 2010)` for instance

**Comment by antagomir** [comment]
Seems to work. I merged into master now.
