### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#129]
Travis fails due to problems in tmap and countrycode installations. Solving this will require finding out more about the required setups.

**Comment by antaldaniel** [comment]
There is a similar problem on R-hub checks.  Because the installation of dependency 'sf' fails on Ubuntu and Fedora, eurostat fails, too. I realized this when I was checking my eurostat-dependent package 'iotables'.

**Comment by antagomir** [comment]
Should work now but if not, happy to hear and check,
