### ISSUE TITLE
get_eurostat data not up to date

### ISSUE THREAD

**Issue by jan-dil** [rOpenGov/eurostat#130]
Hello

I have downloaded this dataset:
dat <- get_eurostat("lfsq_egan2", time_format = "num")

The most recent data I get there for EU28 is for 2018.25, but the Eurostat website offers 2018.5 in this dataset [lfsq_egan2].

Am I doing something wrong?

Thanks!

Best regards

Jan

**Comment by jan-dil** [comment]
Strange, I get more recent data if I change the time_format:
dat <- get_eurostat("lfsq_egan2", time_format = "raw")

**Comment by jan-dil** [comment]
Strange, changing time format seem to have resolved the problem:
dat <- get_eurostat("lfsq_egan2", time_format = "raw")

**Comment by jhuovari** [comment]
I get the latest 2018.5 also with time_format = "num". It could be that the Eurostat updated or/and you get data from eurostat-package cache. Try `clean_eurostat_cache()`

**Comment by jan-dil** [comment]
Thanks, but I still get 2018.5 only for some countries, not for EU28. I get that in "raw" (cached cleared).

**Comment by jhuovari** [comment]
Do you really get 2018.5 for EU28 in "raw"? I don't, and on Eurostat web page only some countries have latest quarter, but not EU aggregates.

**Comment by jan-dil** [comment]
I actually got it from raw and I also see it at the Eurostat website:
http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=lfsq_egan2&lang=en

I attach two screenshots.

<img width="1219" alt="screenshot 2018-12-12 at 13 54 59" src="https://user-images.githubusercontent.com/45793615/49871077-8ab9c980-fe15-11e8-9d75-1346b3f82e5f.png">

<img width="681" alt="screenshot 2018-12-12 at 13 53 28" src="https://user-images.githubusercontent.com/45793615/49871006-58a86780-fe15-11e8-84be-eadcc47769c3.png">

**Comment by jhuovari** [comment]
2018.5 is actually the Q3. Numeric gives the star sof the quarter in numeric format. Like 2018.0, 2018.25, 2018.5 2018.75.

**Comment by jan-dil** [comment]
Oh, I see. I did suspect I was getting something wrong. Sorry for taking your time then!
