### ISSUE TITLE
eu_countries outdated, incompatible with label_eurostat()

### ISSUE THREAD

**Issue by jan-dil** [rOpenGov/eurostat#131]
Please note that eu_countries still includes "Czech Republic". However, label_eurostat() now uses Czechia as the short name for CZ. 

Would it be possible to update eu_countries in the package?

Thanks!

**Comment by jan-dil** [comment]
Just a note that Czechia is correct and has been adopted by Eurostat and other EU institutions and agencies.

**Comment by jhuovari** [comment]
Hmm. eu_countries comes from https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Country_codes_and_protocol_order
They haven't change it (yet). I wouldn't like to tweak it by hand, but yes, it is unconvenient that eu_contries and label_eurostat have different names for CZ.

**Comment by jan-dil** [comment]
I see. I will let Eurostat know then. Thanks!

**Comment by jhuovari** [comment]
Good. Let us now when they update.

**Comment by jan-dil** [comment]
Another problem in that list seems to be Germany. Just dropped it from analysis by accident as label_eurostat() produced Germany in the long form (annoying as it is).

**Comment by jhuovari** [comment]
That is certainly inconvenient.
Should we add a third label-column to those country data.frames?
Or just add warning to documentation?

**Comment by antagomir** [comment]
Warning at least. If the third column could be easily inserted, perhaps it could be useful?

**Comment by jan-dil** [comment]
I expect Eurostat to update Czechia (a colleague contacted them and they tend to react). However, Germany will continue to be a problem. A warning or a third column would be good indeed.

**Comment by jan-dil** [comment]
Eurostat response so far (on Czechia):
"The change of the country name hasn't been done in the tutorial SE article and we are still waiting for a reply. 
We have already sent a kind reminder to the concerned team and we have been informed that the change will be done as soon as possible."

**Comment by jan-dil** [comment]
That was quick in the end: Eurostat fixed Czechia today:
https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Tutorial:Country_codes_and_protocol_order

**Comment by jhuovari** [comment]
Thanks @jan-dil. Now the name is updated and I also added a label column for names in database.
