### ISSUE TITLE
Problems in accessing eurostat data

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#138]
I received the following report that some eurostat data sets are unavailable:

The raw data is available here: https://ec.europa.eu/eurostat/data/database in sector Database by themes => International trade => International trade in goods => International trade in goods – detailed data. 

Tables EU trade since 19988 by CN8 (DS-016890) and EU trade since 1988 by SITC (DS-018995).

These tables can't be accessed with the function `get_eurostat()`. 

I also searched this site for bulk download https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&dir=metadata but I found that these tables are not mentioned.  

Is there another way to download DS-016890 and DS-018995 data?

**Comment by antagomir** [comment]
I have no immediate answer and have to check in more detail. Ping @jhuovari - do you have a sense on this? I did manage to access the data through the web portal but could it still be the case that the mentioned tables are not part of the open data portal?

**Comment by jhuovari** [comment]
There are those trade and productions datasets that are not part of the normal eurostat database and thus not accessible by our packages. This is related to #110 .

**Comment by antagomir** [comment]
Ah yes, exactly. Thanks!
