### ISSUE TITLE
Orphaned package?

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#139]
I received a very strange message today about my iotables package which deals only with Eurostat's input-output tables. 

> ​This requires the orphaned package eurostat which now fails its checks 
(and has done for a few days).  It needs to be archived.

>
- submit a version of iotables that does not require eurostat
- take over maintenance of eurostat
- incorporate the parts of eurostat you need into iotables
- withdraw iotables.

I have no idea what is this and I wrote a letter that it must be some misunderstanding, but it seems that on some systems eurostat is failing to build.

**Comment by antagomir** [comment]
Thanks! I have to check. NOt intended at all!

**Comment by antagomir** [comment]
I had not received some "please fix this" messages. Not sure if it went to spam folder. Therefore they had deprecated the pkg. Now it is there again. https://cran.r-project.org/web/packages/eurostat/index.html and I hope all is OK

**Comment by maartenzam** [comment]
Just tried to install the package on RStudio Cloud and got this error, suspect it is related to this issue:

> > install.packages("eurostat")
> Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4’
> (as ‘lib’ is unspecified)
> trying URL 'http://package-proxy/src/contrib/eurostat_3.3.4.tar.gz'
> Content type 'application/x-gzip' length 4574982 bytes (4.4 MB)
> ==================================================
> downloaded 4.4 MB
> 
> * installing *source* package ‘eurostat’ ...
> ** package ‘eurostat’ successfully unpacked and MD5 sums checked
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** preparing package for lazy loading
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/readr/libs/readr.so':
>   /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/readr/libs/readr.so: undefined symbol: R_ContinueUnwind
> ERROR: lazy loading failed for package ‘eurostat’
> * removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/eurostat’
> Warning in install.packages :
>   installation of package ‘eurostat’ had non-zero exit status

**Comment by antagomir** [comment]
We are still fixing something new in CRAN. Does this work for you meanwhile:

`devtools::install_github("ropengov/eurostat")`

**Comment by maartenzam** [comment]
Hm, no, that gives me the same error.

**Comment by antagomir** [comment]
The pkg has now been updated to CRAN. Does install.packages("eurostat") work now?

**Comment by maartenzam** [comment]
No, I'm still getting an error:

```
> install.packages("eurostat")
Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'http://package-proxy/src/contrib/eurostat_3.3.5.tar.gz'
Content type 'application/x-gzip' length 4561923 bytes (4.4 MB)
==================================================
downloaded 4.4 MB

* installing *source* package ‘eurostat’ ...
** package ‘eurostat’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/readr/libs/readr.so':
  /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/readr/libs/readr.so: undefined symbol: R_ContinueUnwind
ERROR: lazy loading failed for package ‘eurostat’
* removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.4/eurostat’
Warning in install.packages :
  installation of package ‘eurostat’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpnmocBb/downloaded_packages’
```

**Comment by antagomir** [comment]
It seems to me based on search engines that the dyn.load error is common, and often related to missing dependencies in the local system. This might be difficult to solve in the R package itself, although I would be open to proposed solutions. Have you tried to check any of the dyn.load error solutions that you can find by web searches? The solutions may vary and I am not sure what would work best in your case.
