### ISSUE TITLE
Vignette failure

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#140]
The ten00081 data set does not seem to be available any more, making this example broken (eurostat_tutorial.Rmd / line 251). https://github.com/rOpenGov/eurostat/blob/3e253d9df083ba373a6f72e915f0530f3d050f6a/vignettes/eurostat_tutorial.Rmd#L251 

As an immediate fix I set eval=FALSE in the devel branch. Ideally this example can be updated, or removed if update is not feasible.

**Comment by muuankarski** [comment]
Should now work with this:
https://github.com/rOpenGov/eurostat/commit/59a837133ba778c1c30e3a2d09ef2e5b3d213557

**Comment by antagomir** [comment]
Tnx!
