### ISSUE TITLE
Comparison between `eurostat` and `restatapi` packages?

### ISSUE THREAD

**Issue by briatte** [rOpenGov/eurostat#141]
Hello everyone,

There seems to be a new Eurostat package on CRAN (and GitHub):

https://cran.r-project.org/package=restatapi

> restatapi: Search and Retrieve Data from Eurostat Database
>  
> Eurostat is the statistical office of the European Union and provides high quality statistics for Europe. Large set of the data is disseminated through the Eurostat database (<https://ec.europa.eu/eurostat/data/database>). The tools are using the REST API with the Statistical Data and Metadata eXchange (SDMX <https://sdmx.org>) Web Services (<https://ec.europa.eu/eurostat/web/sdmx-web-services/about-this-service>) to search and download data from the Eurostat database using the SDMX standard.

The author seems to be @mmatyi – hi :)

I'd be interested in a list of similarities and differences between the packages.

**Comment by antagomir** [comment]
Thanks! We will need to have a look, and cite this. Comments on similarities/differences are welcome.

**Comment by antagomir** [comment]
One difference is that [restatapi R package](https://github.com/eurostat/restatapi) provides access through rsdmx, whereas this route is not covered by [eurostat R package](https://github.com/ropengov/eurostat).
