### ISSUE TITLE
Decimal places are missing in data query

### ISSUE THREAD

**Issue by mschnetzer** [rOpenGov/eurostat#142]
Hi everyone, 

I advise my students to use the eurostat package to load data into R. Unfortunately, some of them face the problem that decimal places of numbers are missing when retrieving the data. However, the exactly same code works fine on other machines. Everyone uses the latest versions of R and eurostat. Some students solve the problem by not filtering the data within the eurostat query but loading the whole dataset and filter afterwards, which is not very convenient.

Example:
`get_eurostat("ilc_di01", filters = list(geo = "DE", quantile = "D10", indic_il = "SHARE", time = 2005:2018), time_format = "num")`

Are you aware of any package conflicts or potential settings in R/RStudio that could cause this behavior? Do you have any other ideas?

Thanks a lot for your help,
Matthias

**Comment by antagomir** [comment]
Ouch. I do not have immediate answer to this, seems indeed platform-specific issue. Any tips / solutions / PRs are welcome to solve this.

**Comment by jhuovari** [comment]
With filtering a getting data is done with `get_eurostat_json()` and there with `jsonlite::fromJSON()`. So it is json data from the Eurostat API. It might be issue with how json treats decimal separators in different locale settings.

If you could check how result from json look in those computers with problems.
```
url <- "http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/ilc_di01?geo=DE&quantile=D10&indic_il=SHARE&time=2005&time=2006&time=2007&time=2008&time=2009&time=2010&time=2011&time=2012&time=2013&time=2014&time=2015&time=2016&time=2017&time=2018"

jdat <- jsonlite::fromJSON(url)

# especially:
jdat$ilc_di01$value
```

**Comment by mschnetzer** [comment]
Thanks @jhuovari for your help and suggestion. I asked the students to run your code and it turned out that the problem could be elsewhere. 

As a student has reported back, the eurostat query (both with `get_eurostat` and via JSON) yields decimal places *until* they use `ggsave` (`.svg`-Files) for the first time in a session. Afterwards, neither `get_eurostat` nor your JSON example provides decimals anymore.

They also looked for potential package conflicts but could not find any. For now, all traces lead to problems with `ggsave` - even though this sounds really strange to me. I'm not having this problem so I can't really reproduce the outcome myself.

Thanks!

**Comment by antagomir** [comment]
Great to hear. I will close this for now but let's reopen if there is a need.

**Comment by jhuovari** [comment]
That sounds strange indeed. It might be that ggsave or rather svg device messes somehow location settings and jsonlite ends up treating decimal separators wrongly. You could open an issue on ggplot or jsonlite.
