### ISSUE TITLE
merge_eurostat_geodata

### ISSUE THREAD

**Issue by jessicaRjes** [rOpenGov/eurostat#146]
Hi,

i installed the actual eurostat release via install.packages("eurostat") and library(devtools)
install_github("ropengov/eurostat") after calling merge_eurostat_geodata i get the error message:
_Error in merge_eurostat_geodata(data = tgs_es, geocolumn = "geo", resolution = "1",  :    could not find function "merge_eurostat_geodata"_

Is the function not available anymore? What is the alternative for this function?

Thanks in advance!

**Comment by antagomir** [comment]
Some material was moved to ropengov/eurostat_geodata earlier. It seems we removed this; the idea has been to provide a more throroughly thought package to support eurostat map visualizations & geospatial aspects. We'll have a meeting next Tuesday and will have a look.  @muuankarski may have additional tips meanwhile.

**Comment by jessicaRjes** [comment]
Thanks Antagomir. How was the meeting? Could you have a look? Again: What is the alternative for this function?

**Comment by ketevani** [comment]
I have the same problem with "merge_eurostat_geodata" command. Have you solved it?

**Comment by antagomir** [comment]
Hi - there are new geospatial visualization examples in the [tutorial](https://github.com/rOpenGov/eurostat/blob/master/vignettes/eurostat_tutorial.md). Do these help?

**Comment by muuankarski** [comment]
`merge_eurostat_geodata()` was hidden back in spring 2018 https://github.com/rOpenGov/eurostat/commit/463cf8ab651c5ac0946bccd6cb181bdca964411e as we migrated into `sf`-class. You can join `data.frame`s (or `tbl_df`) with `sf` using `dplyr::*_join()`-functions

**Comment by davidkleman** [comment]
Some simple example of the replacement join intended for merge_eurostat_geodata() would be much appreciated. The cheatsheet on RStudio's website still uses this function.

**Comment by antagomir** [comment]
Since we are not currently supporting `merge_eurostat_geodata() `, after switching to sf class, I would instead propose that we remove this function from cheat sheet, and possibly create alternative examples (suggestions welcome). Any comments?

**Comment by muuankarski** [comment]
We have also updated the cheat sheet at RStudio while ago: 
https://github.com/rstudio/cheatsheets/raw/master/eurostat.pdf
