### ISSUE TITLE
Download data where type = "comext"

### ISSUE THREAD

**Issue by fbiga** [rOpenGov/eurostat#149]
Dear  all,

I am exploring the eurostat package. I noticed that the large majority of data are classified as "dataset" and "table" (both accessible using your package).

```
toc <- get_eurostat_toc()
table(toc$type)

comext dataset  folder   table 
     20    6579    1695    1503
```

I don't understand the meaning of the "comext" type. Can someone explain it to me? Thanks.

I am interested in PRODCOM data (title = "Sold production, exports and imports by PRODCOM list (NACE Rev. 2) - annual data", code = "DS-066341", type = "comext"). But when trying to get the data the following error is shown:

```
get_eurostat("DS-066341")

Error in get_eurostat_raw(id) : DS-066341 does not exist or is not readable. Some datasets are not accessible via the eurostat interface. You can try to search the data manually from the comext database at http://epp.eurostat.ec.europa.eu/newxtweb/ or bulk download facility at http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing or annual Excel files http://ec.europa.eu/eurostat/web/prodcom/data/excel-files-nace-rev.2
```

It seems that those labelled with "comext" cannot be downloaded. Is there a way to get access to these data using R?
Or do you know if these issue is planned to be fixed soon?

I think that if this limitation is known it should be clearly stated in the package documentation.
All the options listed in the error message are really neither user-friendly nor efficient.
Many thanks in advance.

**Comment by antagomir** [comment]
Seems related to #110  . Some data sets are not accessible through the standard interface and this cannot be easily fixed in this R pkg. The `get_eurostat` function already explains some of this. We could try to improve the explanation. If you have a suggestion on how to improve that will help and can be added fast.
