### ISSUE TITLE
URLS changed

### ISSUE THREAD

**Issue by dw006** [rOpenGov/eurostat#15]
Eurostat changed the structure and URLs of their site. Accordingly, some of the functions in eurostat, e.g. getEurostatRaw are not working anymore. I think in getEurostatRaw changing the bulk download url from:

adres <- paste("http://epp.eurostat.ec.europa.eu/NavTree_prod/everybody/BulkDownloadListing?sort=1&file=data%2F", 
        kod, ".tsv.gz", sep = "")

to

adres <- paste("http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2F", 
                 kod, ".tsv.gz", sep = "")
http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2F

should do the trick.

Thank you!

dw006

**Comment by jhuovari** [comment]
Should be already fixed in https://github.com/rOpenGov/eurostat/commit/ca41c62d868a957f11b80627e06e36b4577117b1. Please, update to the latest version and if the problem persist, report again.

Thank you.

**Comment by dw006** [comment]
Not sure what is going wrong. After:

library(devtools)
install_github("eurostat", "ropengov")
library(eurostat)

sessionInfo()

gives

eurostat_0.9.35


toc <- getEurostatTOC()

Error in read.table("
http://epp.eurostat.ec.europa.eu/NavTree_prod/everybody/BulkDownloadListing?sort=1&file=table_of_contents_en.txt",
:
  more columns than column names


Any help how to update (if the above way is wrong) would be appreciated.

Best regards

dw006


2015-01-07 11:20 GMT+01:00 Janne Huovari <notifications@github.com>:

**Comment by jhuovari** [comment]
Seem like the setEurostatTOC() is not updated for th new link. Sorry for that. Will fix it, soon.

**Comment by jhuovari** [comment]
Ok, try to update again. Should work now.
