### ISSUE TITLE
Bibliography wrong date type

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#151]
The function is `get_bibentry()` has a small bug. 

The {year} metadata field must be an integer, but the current version gives a full date as a character. This results in an error with some bibliography manager software, for example, Zotero, which does not read the results of get_bibentry when saved as a text file. 

Instead of saving the full date, I created a version that saves {year}, {month}, {day}, which is more exact, and can work with more bibliography styles, too. 

The updated function uses lubridate, which is part of tidyverse for some time. I think generally it would be a good idea to use the more standardized date management of lubridate in eurostat. If this is a problem, it can be omitted, but I am uncertain if the last_update in the toc will always follow the same date pattern. 

I put this version of the function to the 'bibliography' branch.

**Comment by antagomir** [comment]
Thanks! The version from devel branch has now been added to devel and master after minor changes.
