### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#168]
I am not sure if you aware of it, but all articles are unavailable on the website.

**Comment by antagomir** [comment]
Thanks, wasnt aware and aim to fix today.

**Comment by antagomir** [comment]
Ok seems to work again. We have to push the devel changes into master so they become visible. 

I had to remove vignettes/website/regional_data.Rmd for the time being since I did not manage to render it automatically. We can continue checking that separately, and I am closing this one now.
