### ISSUE TITLE
API version

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#170]
The `get_eurostat_json.R` function is now updated to use API v2.1. However its structure has changed somewhat from v1.1, and we have not thoroughly tested that the outputs are correct. No mistakes have been spotted but the output should be checked systematically against the eurostat website using various queries (or automated check of all output) in order to verify correct performance.

**Comment by antagomir** [comment]
@antaldaniel you mentioned having some automated benchmarks to eurostat data; to what extent it might apply here as a validation; and is the code available?

**Comment by pitkant** [comment]
The issue described in this issue seems to refer to API calls that are deprecated and not applicable to the current situation. If anyone experiences similar problems exist please open a new issue. Closed with the CRAN release of package version 4.0.0.
