### ISSUE TITLE
Travis fails with all_of

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#175]
We still have a failure in Travis CI with the all_of function. Could we replace this (all_of) with something else? I already tried to improve definitions in DESCRIPTION file and R/firstlib.R with no success.

** byte-compile and prepare package for lazy loading

Error: object ‘all_of’ is not exported by 'namespace:tidyselect'

Execution halted

ERROR: lazy loading failed for package ‘eurostat’

* removing ‘/home/travis/build/rOpenGov/eurostat/eurostat.Rcheck/eurostat’

R CMD check failed

**Comment by antaldaniel** [comment]
Hi, I removed all_of and rewrote the functio. Curiously dplyr suggested to use it in a join, but it is not necessary. Is it still failing?

**Comment by rameman** [comment]
Hi, thanks for all. I'm using this code. I think it is my problem.

`sp_data <- eurostat::get_eurostat("tag00098",
                                  time_format = "raw",
                                  stringsAsFactors = FALSE) %>%
  dplyr::filter(time == 2010, nchar(geo) == 4) %>%
  dplyr::mutate(ha = cut_to_classes(values, n = 5))`

> `Reading cache file C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/tag00098_raw_code_FF.rds
> Table  tag00098  read from cache file:  C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/tag00098_raw_code_FF.rds
> Error in sVar[1:(length(sVar) - 1)] : 
>   solamente 0's pueden ser mezclados con subscritos negativos
> Además: Warning messages:
> 1: In classInt::classIntervals(x, n = n, style = style) :
>   n greater than number of different finite values\nn reset to number of different finite values
> 2: In classInt::classIntervals(x, n = n, style = style) :
>   n same as number of different finite values\neach different finite value is a separate class`

### `library(eurostat)
library(dplyr)
library(ggplot2)
dat <- get_eurostat("sdg_02_40", time_format = "raw", stringsAsFactors = FALSE) %>% 
  # subsetting to year 2014 and NUTS-2 level
  dplyr::filter(time == 2014, nchar(geo) == 4) %>% 
  # classifying the values the variable
  dplyr::mutate(cat = cut_to_classes(values))`

> Reading cache file C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/sdg_02_40_raw_code_FF.rds
> Table  sdg_02_40  read from cache file:  C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/sdg_02_40_raw_code_FF.rds
> Error in classInt::classIntervals(x, n = n, style = style) : 
>   single unique value

**Comment by rameman** [comment]
I'd like to ask you another question. Is it possible to keep the geographic lines in a map. It'll be nice to see  it in the last map on this[ example](http://ropengov.github.io/eurostat/articles/website/maps.html). France there isn't lines. Is it possible to activate? Thanks.

**Comment by antagomir** [comment]
Seems to work now.
