### ISSUE TITLE
Differences between "TG" and "SDG" categories?

### ISSUE THREAD

**Issue by rameman** [rOpenGov/eurostat#176]
I'm trying to use "sdg" categories by eurostat but I can`t use it. When I use for example "TAG00123" all is correct but I have some errors with this file: "sdg_02_40". Could use "SDG" or is only for "TAG"? Thanks and sorry I'm starting in R recently.

**Comment by antaldaniel** [comment]
rameman, can you expand a bit which statistics is exactly you are trying to use (it must have a product code) and with what function?

**Comment by rameman** [comment]
Hi, thanks for all. I'm using this code. I think it is my problem.

sp_data <- eurostat::get_eurostat("tag00098", time_format = "raw", stringsAsFactors = FALSE) %>% dplyr::filter(time == 2010, nchar(geo) == 4) %>% dplyr::mutate(ha = cut_to_classes(values, n = 5))

    Reading cache file C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/tag00098_raw_code_FF.rds Table tag00098 read from cache file: C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/tag00098_raw_code_FF.rds Error in sVar[1:(length(sVar) - 1)] : solamente 0's pueden ser mezclados con subscritos negativos Además: Warning messages: 1: In classInt::classIntervals(x, n = n, style = style) : n greater than number of different finite values\nn reset to number of different finite values 2: In classInt::classIntervals(x, n = n, style = style) : n same as number of different finite values\neach different finite value is a separate class

Another:

`library(eurostat)
library(dplyr)
library(ggplot2)
dat <- get_eurostat("sdg_02_40", time_format = "raw", stringsAsFactors = FALSE) %>%
# subsetting to year 2014 and NUTS-2 level

dplyr::filter(time == 2014, nchar(geo) == 4) %>%
# classifying the values the variable

dplyr::mutate(cat = cut_to_classes(values))`

    Reading cache file C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/sdg_02_40_raw_code_FF.rds
    Table sdg_02_40 read from cache file: C:\Users\rafam\AppData\Local\Temp\RtmpgJhhYj/eurostat/sdg_02_40_raw_code_FF.rds
    Error in classInt::classIntervals(x, n = n, style = style) :
    single unique value

**Comment by antaldaniel** [comment]
Well, there are two things here.

For tutorials please refer to the stackoverflow website. This is only fir reporting errors. 

The message says that you cannot create categories because you have only a single value.  

However, in a few days we’ll release many new features and a new tutorial vignette on CRAN. 

You can already install it from the devel version.
