### ISSUE TITLE
get_eurostat_dic retrieves html

### ISSUE THREAD

**Issue by Hauke-B** [rOpenGov/eurostat#178]
I fear there is an issue with the get_eurostat_dic function.
When I execute the following code: 
`get_eurostat_dic("sts_inpr_m", lang="en")`
where "sts_inpr_m" is the data set for industrial production, the return is a dataframe with html code. 
The same is true for the dummy example given in your handbook:
` get_eurostat_dic("crop_pro")`.

Probably eurostat changed their html-tree?

Kind regards
![eurostat-dict](https://user-images.githubusercontent.com/42959576/78155921-5b7e0000-743e-11ea-8299-c6880eaf24b0.JPG)

**Comment by jhuovari** [comment]
For the "sts_inpr_m" it seems that the eurostat does not have dictionary: https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&dir=dic%2Fen

We probably should add error message for missing dictionaries.

For the "crop_pro" I do get a proper dictionary. So there could be something else wrong. I am closing this, but you could post what you get for crop_pro, if the problem persists.
