### ISSUE TITLE
Error message for missing dictionary to get_eurostat_dic

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#179]
We should add an error message for missing dictionary to get_eurostat_dic. 
See #178

**Comment by pitkant** [comment]
In the new API SDMX 2.1 (Dissemination API) metadata for datasets can be fetched as XML files (and occasionally JSON/TSV files):
https://wikis.ec.europa.eu/display/EUROSTATHELP/API+SDMX+2.1+-+metadata+query

Maybe this would be more robust against missing dictionaries? I have tested implementing these types of functionalities in smaller functions: `label_eurostat_tables` and `label_eurostat_vars` in #270 

`dimlst.dic` and `table_dic.dic` may not be available but something similar might be available, according to the answer I got from Eurostat user support:

> As of early October 2023, a new URL for files retrieval within Eurostat API will be made available  and phasing out of the Bulk Download Listing (https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing) will start.
>
>Both URL endpoints will be available for a few weeks and distribute the same content without change.
>
>At the end of the transition phase some files will not be produced anymore and /dic/{en,fr,de} will not exist (codelists files).
>
>Nevertheless, there will be the option to retrieve all codelists in XML and to retrieve the inventory listing of codelists. Detailed information will be published in the online help [API for data access - Eurostat Online Help for Data Browser - EC Public Wiki (europa.eu)](https://wikis.ec.europa.eu/display/EUROSTATHELP/API+for+data+access) in the coming weeks.

**Comment by pitkant** [comment]
This seems to now be a vintage issue that is not applicable to the current CRAN released version of the eurostat package, 4.0.0. If the problem persists with the new implementation or if similar problems come up please open a new issue.
