### ISSUE TITLE
label_eurostat

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#18]
Would be useful to keep both label and original id in the output table from label_eurostat ?

**Comment by jhuovari** [comment]
Yes, that would be useful option. What would be naming convention if both kept? Add suffix "_code"?

**Comment by antagomir** [comment]
How about "id" and "id_name" ? 

Btw I was thinking that perhaps labeling could be provided automatically already in the get_eurostat output

Related to this, I combined get_eurostat and get_eurostat_raw, see the output argument of get_eurostat now. Earlier experience has shown that changing arguments is less confusing for users than having multiple separate download functions.

**Comment by jhuovari** [comment]
I would go with "id" and "id_code". Labels (or names) are more natural.

Labeling could be done automatically, but I would produce by default only either labels or codes. Having multiple variables with basically the same information is not optimal.

`get_eurostat_raw()` should definately be just internal function or inside `get_eurostat()`. I didn't considered it as a separate download function. Having it as separate internal could be easier for debugging. 

But either way, personally I don't think we need to provide a "molten" output option.

**Comment by antagomir** [comment]
Right, perhaps you are correct that it is not optimal. In fact I sort of like to label_eurostat function already in its current form. This might be less error-prone as the output table; it is useful that get_eurostat will always have standard column names.

I have changed get_eurostat_raw to an internal function and it is now called within get_eurostat.

I agree that it is not necessary to provide "molten" output. This is a standard transformation in any way and easily done by the user when needed. I kep it here because the get_eurostat provided this and I did not want to remove yet. My suggestion is to remove the "molten" output option (and output argument) from get_eurostat. If useful, we can show in the vignette how to melt the data.

**Comment by jhuovari** [comment]
I agree with all your points. 

It would be, however, useful to have an option in `label_eurostat` to retain also code information. And also by variable basis. 

But not essential. Easy to done also without an option.

**Comment by antagomir** [comment]
I now removed "molten" output from get_eurostat. And moved tidy_eurostat outside of it as a separate function (example now in vignette). The tidying up will include running tidy_eurostat and label_eurostat. It would be good to develop a single unified function that takes care all of that, possible with different options and a good default. I will leave this open now for anyone to propose a fix & send a pull request.

**Comment by jhuovari** [comment]
Sorry, I wrote my earlier replay without thinking too much. I think it is the molten output that is the only one that `get_eurostat()` should return. And I think moving `tidy_eurostat()` outside `get_eurostat()` is a really bad idea. First, it will break backward compatibility. (all my code, argh). Second, the tidy, molten, form is the useful format. The original eurostat wide format is pretty useless in R.

Sorry again, that I gave a wrong idea.

**Comment by antagomir** [comment]
Ok, I see. My logic went differently since way back there was discussion with other packages that it is always good to have the option to retrieve the raw data separately if needed. But I also prefer pragmatic approach. For some people the table format might be useful since people may wish to print or view the tables, or they only know how to use more simple plotting operations (molten format more or less assumes ggplot2 for visualization). 

Therefore I would keep the table format available. I propose that get_eurostat will have two output options: molten and table (or perhaps 'long' and 'wide'). The long option can be the default if you need for your code, otherwise I would propose that the wide option is the default.

Perhaps the labeling function can be kept separate then. It is just one additional line of code anyway and quite clear from the example.

I am planning to submit the package to CRAN after one week from now. I may still add these features if I find the time but not sure. If you have a chance to make this fix it would be welcome. Also other comments or improvement to the pkg are welcome now as the submission is approaching.

Leo

**Comment by jhuovari** [comment]
Sometimes a wide (or table) might be useful, but not that of Eurostat. Also useful wide tables have variable names on column names and their values on that column. The raw Eurostat table have time variable values on column names, and in character form. And the first column have all other variables comma separated.

I don't think, you can't use that for any reasonable simple plotting or anything else.

I strongly believe that the long, tidy, format should be the default. We could have also the wide format option, but not that of `get_eurostat_raw()`. That you really can't use without further formatting for anything.

**Comment by jhuovari** [comment]
I might have some time on Sunday to do preparing for the submission.

**Comment by antagomir** [comment]
For me ok to have the long as default. 

Having wide available would be quite useful, too, but I agree it would need to be cleaned up before returning to the user. Perhaps this is easily achieved by modifying the tidy_eurostat which already makes much of that.

If you have a chance that would be great. Being able to complete the remaining issues and submitting to CRAN soon is a good target now,

**Comment by pbiecek** [comment]
CRAN submission is a very good idea, 
I am using this package for some hands-on trainings but for some users the installation from github is too painful. 

IMHO long as default is ok, 
wide is useful, but since number of dimensions is different for different Eurostat tables different users might be interested in different wide formats.

**Comment by jhuovari** [comment]
I reverted `get_eurostat()` back to a long format. What about the wide? As @pbiecek said there is a choice which wide. All eurostat dimensions could include variables, except the time. So all other wide formats than the eurostat raw table are possible. The time as "wide varible" is also impossible, because it will produce illegal column names. 

The wide format has also the drawback, that with it you lose the dimension name of the "wide variable". For example if we put countries on columns there are nowhere to record that columns comes from the geo variable (/dimension).

**Comment by antagomir** [comment]
Ok. How about just making one or two examples in vignette on how to convert from long to wide and print a table with kable? This would be helpful for naive users.

**Comment by jhuovari** [comment]
Added some examples and edited vignette in 36b8cf75461752292dc1e55c3101262448d4d531.
