### ISSUE TITLE
Eurostat data changed - old R package still available?

### ISSUE THREAD

**Issue by Erich-St** [rOpenGov/eurostat#184]
Hi, 
I was wondering if the version of the "eurostat" R-package from December 20th, 2019 was still available for download somewhere. Since several countries' NUTS-regions changed since then, my code is not running anymore.
Regards,
Erich

**Comment by antagomir** [comment]
Did you try and recover the older version from Gitlab history? With version control you are able to recover any past version. Let us know if this does not work.

**Comment by antagomir** [comment]
.. to add: there are at least two ways I think, 1) identify the exact version from github history, clone the package, switch to the previous commit of choice and install it locally with devtools::install(); or you can browse CRAN versions, all old CRAN packages should also be available as a downloadable file and can be installed locally.

**Comment by Erich-St** [comment]
Thank you for the quick response! I was able to recover several older versions of the package, but the problem is still there. My hunch is that each package version loads whatever Eurostat has on the webpage. So my problem doesn’t come from the package, but from the update on the Eurostat page. Can you confirm this?

Kind regards,
Erich

**Comment by antagomir** [comment]
Yes, I think so. Our package aims to provide access to the data as is. It is unfortunate that changes in the data do sometimes break workflows, I hope it is not a major fix and let us know if there is anything related to the R pkg where might be able to help.

**Comment by Erich-St** [comment]
Thanks for the feedback!

Maybe there could be a built-in user warning popping up right when the package is loaded in R.

Thanks again for a great package!

Erich


On 14.07.2020, at 17:08, Leo Lahti <notifications@github.com> wrote:

﻿

Yes, I think so. Our package aims to provide access to the data as is. It is unfortunate that changes in the data do sometimes break workflows, I hope it is not a major fix and let us know if there is anything related to the R pkg where might be able to help.
