### ISSUE TITLE
combination of add_nuts_level() and label_eurostat() does not work properly

### ISSUE THREAD

**Issue by michielvandijk** [rOpenGov/eurostat#186]
I am combining the functions add_nuts_level() and label_eurostat() but somehow the functions interfere. 

For example, this works fine, resulting in a correct nuts_level column:
df <- get_eurostat("agr_r_accts") %>%
  add_nuts_level(geo_labels = "geo") 
  
But when I run this: 
df2 <- df %>%
  label_eurostat(code = "geo", fix_duplicated = TRUE) 

I get the message:
Warning message:
In label_eurostat(y[[i]], i, eu_order = eu_order, lang = lang, countrycode = countrycode,  :
  All labels for nuts_level were not found.

and the nuts_level column gets mixed up.

I also tried a different order, not keeping the code columns, different datasets, etc but somehow the label_eurostat() function wants to identidy the nuts level as well, which fails, perhaps because there are duplicated labels?

**Comment by antaldaniel** [comment]
I think that we should connect this to the regions package, and make a vignette about working with subnational statistics. The duplication comes from the problem that the [regions](https://regions.dataobservatory.eu/) package solves: often in the same dataset the same geo is present with two different definitions.  This is a bug on Eurostat's side, not on the eurostat packages.

**Comment by antaldaniel** [comment]
These functions will be deprecated as a new package grew out of them, which is already on CRAN under the name [regions](https://regions.dataobservatory.eu/).  On the devel branch there is a new tutorial, and the functions give a message or warning, and when appropriate, call the regions function instead. 

@antagomir , @michielvandijk , I think that this issue can be closed as soon as the devel branch is merged to the master.

**Comment by antagomir** [comment]
Done in #217
