### ISSUE TITLE
How to show labels and not codes in final analysis outputs

### ISSUE THREAD

**Issue by sbacelar** [rOpenGov/eurostat#187]
After downloading a file I used SELECT and FILTER and I have done other data transformations. I have used `codes` and not `labels` but in the end I want my final output table showing `labels`, not `codes`. How may I do that?

**Comment by antagomir** [comment]
Can you provide a reproducible example and indicate what is missing?

**Comment by sbacelar** [comment]
In the following example, I got some data from DK and UK and have done some data transformations. But in the final table I don't want to show DK and UK but Denmark and the United Kingdom. How to that _a posteriori_ without using `label_eurostat(dat)` in the first place? That is how to transform `dat_2_wide` to show Denmark and United Kingdom instead of DK and UK?  Another question: how to show every year from 2004 to 2019 even if there is no data in 2006 and 2007?

```
library(tidyverse)
library(eurostat)
dat <- get_eurostat(id="env_ww_con", time_format="num")
#> Table env_ww_con cached at C:\Users\sbac\AppData\Local\Temp\RtmpgHHQqH/eurostat/env_ww_con_num_code_FF.rds


dat_2 <- dat %>%
  filter(ww_tp == "TOTAL", unit == "PC", geo %in% c("DK","UK"),
         time %in% 2004:2019) %>%
  select(geo, time, values) %>%
  arrange(time)

dat_2_wide <- dat_2 %>%
  pivot_wider(names_from = time, values_from = values)
dat_2_wide
#> # A tibble: 2 x 10
#>   geo   `2004` `2005` `2008` `2009` `2010` `2011` `2012` `2013` `2014`
#>   <chr>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
#> 1 UK       100    100     97     97   99.5    NA      NA     NA     NA
#> 2 DK        NA     NA     NA    100  100.    100.    100    100    100
Created on 2020-09-14 by the reprex package (v0.3.0)
```

**Comment by antagomir** [comment]
I think we don't have a shortcut for that. The mappings between country codes and country names should be done manually, or label_eurostat could be used to retrieve mappings first. 

A shortcut could be added perhaps. I will leave this open now, as potential feature to add. Pull requests are welcome and can speed it up.

**Comment by jhuovari** [comment]
Do you mean like this:

```
dat_2_wide <- dat_2 %>%
   pivot_wider(names_from = time, values_from = values) %>% 
   mutate(geo_lab = label_eurostat(geo, dic = "geo"))
 
dat_2_wide
# A tibble: 2 x 11
  geo   `2004` `2005` `2008` `2009` `2010` `2011` `2012` `2013` `2014` geo_lab       
  <chr>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <chr>         
1 UK       100    100     97     97   99.5    NA      NA     NA     NA United Kingdom
2 DK        NA     NA     NA    100  100.    100.    100    100    100 Denmark   

```

**Comment by sbacelar** [comment]
Thank you. This solved my problem.
