### ISSUE TITLE
Startup message

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#19]
Is it really needed? Do users need to see that information every time they attach the package?

**Comment by antagomir** [comment]
To my knowledge it is not mandatory in any sense to have this. It is however quite standard to have the startup msg afaik. All library startup msgs can be suppressed with suppressPackageStartupMessages if necessary.  In a way it is nice to display information on authors and pkg homepage though I am not sure how useful this is in the end. We can consider this.

**Comment by antagomir** [comment]
Ok, I removed this then.
