### ISSUE TITLE
Can't install: Dependency RefManageR has been removed from CRAN

### ISSUE THREAD

**Issue by trianglegirl** [rOpenGov/eurostat#195]
RefManageR has been archived on CRAN
Eurostat has also been archived on CRAN because it's now missing a dependency
This package cannot be installed as RefManageR is a dependency of eurostat

Perhaps listing RefManageR as a dependency from GitHub would help as a temporary fix.
Made PR #194

**Comment by trianglegirl** [comment]
Actually - it seems like RefManageR is in the middle of a fix, so this might be back up on CRAN in a few days - hopefully. Making this redundant.

**Comment by jhuovari** [comment]
Seems like RefManageR is back on CRAN. Can we expect eurostat there as well soon, @antagomir ?

**Comment by antagomir** [comment]
Oh great. We have been emailing back and forth with RefManageR developer and I have already tried to submit a version where RefManageR was removed. But now I will add it back. This is very recent news, thanks for the update. We will submit this today but given the troubles with CRAN, there are no guarantees yet how rapidly we get through the process again.

**Comment by jhuovari** [comment]
Great, thanks!

**Comment by antagomir** [comment]
eurostat is now back in CRAN
