### ISSUE TITLE
filter by country leads to error

### ISSUE THREAD

**Issue by sakaiando** [rOpenGov/eurostat#208]
I tried to download data for a small subset of countries using the code below.

```
library(eurostat)
df<-get_eurostat(id ='bop_c6_a', filters = list(geo = list(c('EE','LV'))))
```

But the code leads to the following error.

 >Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  The requested url cannot be found within the get_eurostat_json function: http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/bop_c6_a?geo=EE&geo=LV

Could you kindly advise how to fix the error?

Here is the session info.

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices datasets  utils     methods   base     
> 
> other attached packages:
>  [1] eurostat_3.6.1  forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5     purrr_0.3.3     readr_1.3.1     tidyr_1.0.2     tibble_2.1.3   
>  [9] ggplot2_3.3.0   tidyverse_1.3.0
> 
> loaded via a namespace (and not attached):
>  [1] xfun_0.12          tidyselect_1.0.0   sf_0.8-1           haven_2.2.0        lattice_0.20-40    colorspace_1.4-1  
>  [7] vctrs_0.2.4        generics_0.0.2     yaml_2.2.1         utf8_1.1.4         rlang_0.4.5        e1071_1.7-3       
> [13] pillar_1.4.3       glue_1.3.2         withr_2.1.2        DBI_1.1.0          sp_1.4-1           dbplyr_1.4.2      
> [19] RColorBrewer_1.1-2 modelr_0.1.6       readxl_1.3.1       lifecycle_0.2.0    plyr_1.8.6         munsell_0.5.0     
> [25] gtable_0.3.0       cellranger_1.1.0   rvest_0.3.5        knitr_1.28         curl_4.3           class_7.3-15      
> [31] fansi_0.4.1        broom_0.5.5        Rcpp_1.0.3         KernSmooth_2.23-16 scales_1.1.0       backports_1.1.5   
> [37] classInt_0.4-2     jsonlite_1.6.1     countrycode_1.1.1  fs_1.3.2           hms_0.5.3          stringi_1.4.6     
> [43] grid_3.6.3         bibtex_0.4.2.2     cli_2.0.2          tools_3.6.3        magrittr_1.5       RefManageR_1.2.12 
> [49] crayon_1.3.4       pkgconfig_2.0.3    ellipsis_0.3.0     xml2_1.2.5         reprex_0.3.0       lubridate_1.7.4   
> [55] assertthat_0.2.1   httr_1.4.1         rstudioapi_0.11    R6_2.4.1           units_0.6-5        nlme_3.1-145      
> [61] compiler_3.6.3

**Comment by jhuovari** [comment]
With filters the Eurostat api is limited to 50 categories. So, you have to limit filters more or get data without filter option.

However, the error message is missleading.

**Comment by sakaiando** [comment]
Thanks jhuovari,

Indeed, if I add more criteria in filters, the data is properly downloaded!

```
library(eurostat)
df <- get_eurostat(id = 'bop_c6_a',
                   filters = list(
                     geo = c('LV','EE','DE','AT'),                          #  latvia, estonia, germany, austria
                     partner = 'WRL_REST',                   # rest of the world
                     currency = 'MIO_EUR',                   # million euro
                     bop_item = c('CA','G','S','IN1','IN2'), #currency account, goods, services, primary income, secondary income
                     sector10 = 'S1',                        # total economy
                     sectpart = 'S1',                        # total economy
                     stk_flow = 'BAL'                        # balance
                   ))
```

What does 50 "categories" mean? The above code will download 780 observations of 9 variables, but how to count "categories"? I checked documentation but found only the following explanation...

> Queries are limited to 50 sub-indicators at a time.

**Comment by umbe1987** [comment]
Indeed, I had the same issue and I could not figure out what does `50 categories` mean actually.

> Thanks jhuovari,
> 
> Indeed, if I add more criteria in filters, the data is properly downloaded!
> 
> ```
> library(eurostat)
> df <- get_eurostat(id = 'bop_c6_a',
>                    filters = list(
>                      geo = c('LV','EE','DE','AT'),                          #  latvia, estonia, germany, austria
>                      partner = 'WRL_REST',                   # rest of the world
>                      currency = 'MIO_EUR',                   # million euro
>                      bop_item = c('CA','G','S','IN1','IN2'), #currency account, goods, services, primary income, secondary income
>                      sector10 = 'S1',                        # total economy
>                      sectpart = 'S1',                        # total economy
>                      stk_flow = 'BAL'                        # balance
>                    ))
> ```
> 
> What does 50 "categories" mean? The above code will download 780 observations of 9 variables, but how to count "categories"? I checked documentation but found only the following explanation...
> 
> > Queries are limited to 50 sub-indicators at a time.

**Comment by jhuovari** [comment]
It is combination of selections in variables. In above there are 20 combinations (4*1*1*5*1*1*1) It's explained here: https://ec.europa.eu/eurostat/web/json-and-unicode-web-services/data-scope-and-query-size

But, the limit seems to be higher nowdays, at least I am able to download more than 50 categories.

**Comment by umbe1987** [comment]
> It is combination of selections in variables. In above there are 20 combinations (4_1_1_5_1_1_1) It's explained here: https://ec.europa.eu/eurostat/web/json-and-unicode-web-services/data-scope-and-query-size
> 
> But, the limit seems to be higher nowdays, at least I am able to download more than 50 categories.

The link does not seem to work anymore (at least from my side).
