### ISSUE TITLE
Rename grepEurostatTOC to search_eurostat_data?

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#21]
Would it be clearer? grep does not probably tell everyone what the function does.

**Comment by antagomir** [comment]
Ok for me. It could also simply be search_eurostat

**Comment by jhuovari** [comment]
Done in 270f5baf38b24bf66d613dfac914f33aa6a5dfeb.

I also changed all remaining camelCase names:
* grepEurostatTOC() to search_eurostat()
* setEurostatTOC() to set_eurostat_TOC()
* getEurostatTOC() to get_eurostat_TOC()
* getEurostatDictionary() to get_eurostat_dic()

Old functions are deprecated to remove later.

I also added 2 tests and updated vignette for new names.

**Comment by antagomir** [comment]
I would propose using lowercase everywhere. I see no point in mixins uppercase and lowercase when cameCase is not used. It can also be confusing when some functions are fully lowercase (get_eurostat_dic and others partially uppercase as the TOC functions). Any comments ?

**Comment by jhuovari** [comment]
I thought it also. And now all are lower case.
