### ISSUE TITLE
Problems accessing data from R --You have not access to ec.europe.eu. 

### ISSUE THREAD

**Issue by diegomallada** [rOpenGov/eurostat#210]
Hi, 

Im trying several datasets (it worked perfectly last week) and get this error
You have no access to ec.europe.eu. 
      Please check your connection and/or review your proxy settings

This is the line code

library(eurostat)
datoss <- get_eurostat("rd_e_gerdtot", time_format = "date")

**Comment by antagomir** [comment]
Works for me. Can you confirm the package version numbers you're using? Or is this a temporary problem.

**Comment by antaldaniel** [comment]
I cannot put my finger on the problem, but I think that this has something to do with the user's R session and how it works with RCurl.  I was trying to figure out myself similar problems, and realized that re-starting R (at least often) solves the problem.

**Comment by antagomir** [comment]
This problem may be out of scope to solve in eurostat package. I suggest to close this issue unless we have a solution in a horizon.

**Comment by antagomir** [comment]
Yes, that's a good minimum solution if we cannot provide other.

**Comment by antagomir** [comment]
Closed via #241 - testing & feedback welcome. Thanks!
