### ISSUE TITLE
Specify that libgdal-dev is necessary to install on Debian/Ubuntu or make the sf package optional

### ISSUE THREAD

**Issue by paulrougieux** [rOpenGov/eurostat#213]
This is a request to :
1. either document the sf dependency and GDAL requirement with an additional error message. 
2. or make the sf dependency optional (since the eurostat data download doesn't depend on it and since GDAL is quite a heavy library to install)

Installation failed on Debian because of a missing GDAL dependency for the sf package. The sf package is itself a dependency of the eurostat package (as visible in the imports of the [DESCRIPTION file](https://github.com/rOpenGov/eurostat/blob/master/DESCRIPTION)). Some packages print a message when the installation fails, that suggest installing the required packages at the system level. The message in this case could be: 

    Please install the GDAL development library 

       sudo apt install libgdal-dev

Maybe this installation instruction should actually be notified when the sf package fails to install? The [Ubuntu dependencies](https://github.com/r-spatial/sf#ubuntu) are actually specified in the sf readme, but a hint in the installation process would make the installation smoother.

**Comment by antagomir** [comment]
Good point.

As a primary solution, I would suggest dropping sf from Dependencies to Imports/Suggests if this helps.

But adding our own Ubuntu (and other) dependencies section in the same way than in sf package would be helpful as well.

**Comment by pitkant** [comment]
Should now be fixed with the package version 4.0.0. If the problem persists please open a new issue.
