### ISSUE TITLE
Better integration with regions

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#218]
I would suggest the following simple integration steps

1. Whenever the user downloads a dataset, and the dataset contains regional geo codes (this can be established with a very quick call) the user gets a message that special care is needed and prompted to review the regional vignette, and/or run validate_nuts_codes.

2. I would import and put into the eurostat documentation the two crucial functions of regions, validate_nuts_code, and recode_nuts, becuase these are essential to work with the regional datasets. The rest of regions (imputations, etc.) should remain there, as they are non-essential and not trivial tasks.

The extra validation step can be done with a very cheap call, as we only have to check the geo code character lenghs, and rule out excpetions like EU27 and EA19, other than these, if the geo codes are longer than 2 characters, i.e. the country codes, validation is almost always  necessary. 

Importing two functions will not add a big burden to eurostat, because the joint vignette will anyway suggest the entire regions package, which, in turn, is not very heavy, it often refers back to eurostat itself.

@antagomir , @pitkant , what do you think?

**Comment by antagomir** [comment]
Sounds good to me at least. Could you make the PR?

**Comment by antaldaniel** [comment]
Included in [PR 220](https://github.com/rOpenGov/eurostat/pull/220/)
