### ISSUE TITLE
Better integration with iotables

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#219]
Similarly to [218](https://github.com/rOpenGov/eurostat/issues/218) I would make a very cheap call and message to downloads  of symmetric input-output tables. This affects about 12 products in the entire Eurostat catalgoue, however, I think it is important, because these special products should not be read as a data frame, but as a strictly formed matrix.  They are meant to be used in input-output matrix equations.  So the downloader with its long-form data frame is useless, and basically the entire point of the iotables R package on rOpenGov to make them useable. 

So, I would add a simple check in the downloader function making sure that if these few codes are in the id parameter, the user gets a message the she should rather download this with the special downloader of iotables. 

The iotables need not become a dependency of eurostat, therefore no extra weight is given to the package.

**Comment by antagomir** [comment]
Yes, really good.

**Comment by antaldaniel** [comment]
Included in [PR 220](https://github.com/rOpenGov/eurostat/pull/220/)
