### ISSUE TITLE
Conflicting value column name

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#22]
I accidentally opened this issue on pxweb side (https://github.com/rOpenGov/pxweb/issues/84).

To recap it briefly here:
At least dataset sbs_pen_7b1 includes variable named value, so as column for values is also called value there would be two columns named value. 

Solutions:
- Change the column for values to `values` as in pxweb. But this will break users existing code.
- Do some dirty fix. Like using VALUE (upper case) for variable name.

If no objections, I will change for `values`

**Comment by antagomir** [comment]
I polished the package and it is starting to look pretty ! Excellent networked collaboartion from all of us. I amazed. When this issue is closed I can submit to CRAN unless there are objections. I propose we  make the suggested change.

**Comment by jhuovari** [comment]
We probably should advertise this, at least on NEWS file.
