### ISSUE TITLE
Potential improvement on cache dir

### ISSUE THREAD

**Issue by dieghernan** [rOpenGov/eurostat#223]
Hi @antagomir 

As you know, I developed [`giscoR`](https://github.com/dieghernan/giscoR) as a kind of spatial spin-off of `eurostat`.

Recently I have been working on improving the cache dir management (previously set as `options(gisco_cache_dir = "path")`, similar to the desing on `eurostat`).  Now the cache is set by storing a persistent path using [rappdirs::user_cache_dir()](https://rappdirs.r-lib.org/reference/user_cache_dir.html), that is loaded as an environment variable at the beginning of the session. 

That means that `options()` command is not needed, in fact the users don't have to worry about the cache any more, that is managed internally by the package. The cache dir can be modified persistently with a custom function (see https://dieghernan.github.io/giscoR/reference/gisco_set_cache_dir.html for Details).

Source code: See https://github.com/dieghernan/giscoR/blob/master/R/gisco_cache.R

If this is something you would like to explore for implementing it also in your package ping me and I could start to have a look on it.

Regards

**Comment by antagomir** [comment]
Hi - that would be great, could you consider a PR?

Also, always welcome to host giscoR in association with rOpenGov for added synergies. Otherwise, we should cross-link in eurostat pkg at least.

**Comment by pitkant** [comment]
Yes, maybe changing from `options("eurostat_cache_dir" = [DIRECTORY_OF_CHOICE])` to rappdirs would better adhere to [Hadley's interpretation of CRAN policies](https://r-pkgs.org/release.html#cran-policies) to not change options without user's consent and be more explicit for the end user. 

Though it must be said that in the current implementation this `getOption("eurostat_cache_dir")` is assumed to be NULL if the user has not explicitly stated another directory. I think most users use the default, which uses the base R `tempdir()` (more precisely `file.path(tempdir(), "eurostat")`)

I don't see any problem in changing this behaviour, maybe moving cache functionality out of `get_eurostat()` and `get_eurostat_geospatial()` (and rewriting `clean_eurostat_cache()` function) would make the code better organised

**Comment by dieghernan** [comment]
Great feedback @pitkant , I would try to prepare a PR tackling all those comments.

@antagomir I am considering your proposal:

> Also, always welcome to host giscoR in association with rOpenGov for added synergies.

Could you please provide more information on this? There are two main topics I am concerned with when transferring repos to organisations:

- Ownership and access rights to the repo after transferring it.
- Integrations with third parties, specifically codecov (that I use for code coverage) and most important zenodo, that provides me with DOIs. Other organisations (as [rOpenSpain](https://github.com/ropenspain/)) didn’t have any problems on activating those services for my repos.

Regards

**Comment by antagomir** [comment]
Re: potential transfer:
- Ownership & access: we can grant the full admin rights to the repo (the admins of the ropengov github organization also have admin rights to all repos, but these would be typically used only in exceptional circumstances)
- We have had no problems with codecov & zenodo, and these have been used

Interesting to learn about rOpenSpain, this was new!

**Comment by dieghernan** [comment]
Good then! If you grant me access happy to join rOpenGov!

Regarding rOpenSpain, is a community of R package developers following the spirit of rOpenSci (the motto is "rOpenSci is our form, Spanish public data our matter"). There is a collection of package that extracts Spanish public data, the webpage is in Spanish:

<https://ropenspain.es/>

See the packages:

<https://ropenspain.es/paquetes/>

And the r-universe (this one on English):

<https://ropenspain.r-universe.dev/ui>

I have a couple of packages included. I also am the webmaster and I developed our pkgdown template. See one of my packages, that leverages on **giscoR**;


https://ropenspain.github.io/mapSpain/

**Comment by antagomir** [comment]
The rOpenSpain shares a lot in common, the starting point for us was Finnish context but there are now many packages with a cross-border coverage.

@pitkant can you check the transfer details with @dieghernan ?

**Comment by pitkant** [comment]
GitHub's [Transferring a repository: Transferring a repository owned by your user account](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) seems to explain the process clearly enough. I will give @dieghernan Owner-level rights in rOpenGov-organization and the transfer should be straightforward after that.

**Comment by dieghernan** [comment]
Aaaand is done!
https://github.com/rOpenGov/giscoR

**Comment by pitkant** [comment]
Great! We can leave this issue open until you a PR about cache dir functionalities is closed.

As a sidenote related to other issues on geospatial functions (e.g. #222 and #213), I should start looking into how Eurostat-package could be improved (and hopefully made more lightweight) by leaning more on separate package, giscoR.
