### ISSUE TITLE
your recent tutorial with updated data

### ISSUE THREAD

**Issue by ptoche** [rOpenGov/eurostat#224]
Great [tutorial](http://ropengov.github.io/eurostat/articles/website/maps.html)! Not sure if this is the place to report: If you subset the eurostat data with 2018 and the geospatial data with 2021, you can get a map with French data. Looks better:

![Rplot](https://user-images.githubusercontent.com/6339274/130305335-34cb2788-fa1f-4ee7-b814-e276298e778e.png)

    # Disposable income of private households by NUTS 2 regions at 1:60mln res
    library(eurostat)
    library(dplyr)
    library(ggplot2)
    data_eurostat <- get_eurostat("tgs00026", time_format = "raw") %>% 
        dplyr::filter(time == 2018, nchar(geo) == 4) %>% 
        # classifying the values the variable
        dplyr::mutate(cat = cut_to_classes(values))

    # Download geospatial data from GISCO
    data_geo <- get_eurostat_geospatial(resolution = "60", nuts_level = "2", year = 2021)

    # merge with attribute data with geodata
    data <- inner_join(data_geo, data_eurostat)

    ## Joining, by = "geo"
    ggplot(data = data) + geom_sf(aes(fill = cat), color = "dim grey", size = 0.1) + 
        scale_fill_brewer(palette = "Oranges") +
        guides(fill = guide_legend(reverse = TRUE, title = "euro")) +
        labs(title = "Disposable household income in 2018",
             caption="(C) EuroGeographics for the administrative boundaries 
                    Map produced in R with data from Eurostat-package <github.com/ropengov/eurostat/>") +
        theme_light() + 
        theme(legend.position = c(.8, .8)) +
        coord_sf(xlim = c(-12, 44), ylim = c(35, 70))

**Comment by antagomir** [comment]
Nice! I have update this to the vignette.
The idea way would be to do a pull request but this worked as well. Contribution appreciated.
