### ISSUE TITLE
get_eurostat folder handling

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/eurostat#226]
Currently search_eurostat can retrieve the following items: 'dataset', 'folder', 'table' (or 'all' of them). get_eurostat function can download datasets and tables but not folders. 

This has led to some confusion whether eurostat package should be able to handle folders as well, by downloading all datasets in a given folder. Another possible enhancement is make eurostat handle folder and dataset hierarchies.

**Comment by antagomir** [comment]
In principle, extending the capabilities to folders would sound good but this has to be balanced with the cost/risk-benefit ratio. Wondering how common use case this would be. We can also leave it for later unless there is a pressing need. 

Documentation could be clarified?

**Comment by pitkant** [comment]
Yes, clarifying documentation would be the easiest fix here

Partly related to #86 (downloading whole migr_asy folder instead of grepping folders that contain 'migr_asy*' or 'migr_*')

**Comment by pitkant** [comment]
Closed with the CRAN release of package version 4.0.0
