### ISSUE TITLE
Error installing package sf.

### ISSUE THREAD

**Issue by JohnU1960** [rOpenGov/eurostat#233]
I am trying to install the eurostat 3.7.9 package along with s2, giscoR and sf.  I want to install them into R 4.1.1 on a CentOS linux computer using RStudio.  Everything is working except that the sf package fails with the error:

`checking for gdal-config... no
no...
configure: error: gdal-config not found or not executable.`

If anyone has information about this error and how I might be able to resolve it please let me know.  Thanks.

**Comment by pitkant** [comment]
We have tried to circumvent this issue by making a minimal installation without sf package now possible. If the problem persists, please open a new issue.

Closed with the CRAN release of package version 4.0.0
