### ISSUE TITLE
Eurostat open data portal?

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#24]
I think referring to the Eurostat open data and open data portal is bit misleading. Eurostat do have the Open data portal (https://open-data.europa.eu/en/) and it's have an API (https://open-data.europa.eu/en/developerscorner). The package, however, do get its data from the Eurostat main database and the reference on README is for the Eurostat main page. The open portal do get its data from the same source, but to refer to the Open data portal, we should use their API. I think the CRAN was also complaining about this also on their comment.

The Description also has "together with analysis and visualization utilities." I don't think we really have any of those, at least yet.

**Comment by antagomir** [comment]
Ah ok, good point.. I have been too ignorant. Now I wonder what's the difference between the two if they provide the same data anyway but this does not affect our package now. This must be changed before submission. 

Analysis & visualization utilities can be there or can be removed.

**Comment by jhuovari** [comment]
I don't know. I actually just discovered the open portal when I did googling for the Eurostat open data. But I think their api could be something to look for in the future. Maybe it gives a option to download one series at time.

**Comment by jhuovari** [comment]
Fixed this on af35ba22adeb9075049c94b646e245c5a99dd72e
