### ISSUE TITLE
Trying to use get_eurostat with filters but failing in doing so

### ISSUE THREAD

**Issue by umbe1987** [rOpenGov/eurostat#244]
I am using this query

```
get_eurostat(
    id = "migr_pop1ctz",
    time_format = "num",
    filters = list(
      geo = "UA",
      sex = "T",
      citizen = "UA",
      unit = "NR",
      time = 2021
    )
  )
```

but I receive this error:

```
Error in if (nchar(times[1]) > 7) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In is.null(filters) || filters != "none" :
  'length(x) = 5 > 1' in coercion to 'logical(1)'
2: Unknown or uninitialised column: `time`. 
```

What am I doing wrong?

Thank you

**Comment by jhuovari** [comment]
Nothing. There just do not seems to be data with that spesification.

**Comment by umbe1987** [comment]
Indeed, I just checked and by defining `citizen = "UA"` there don't seem to be any data available.
Thanks for your feedback.
Still, is it correct that the API responds throwing an error?
Wouldn't it be better to return an empty dataframe (or similar object)?
BTW, thank you for making this useful API available.

**Comment by jhuovari** [comment]
Yes, that is a good idea.
