### ISSUE TITLE
eu_countries and eu_candidate_countries outdated

### ISSUE THREAD

**Issue by espinielli** [rOpenGov/eurostat#245]
I noticed that the `eu_countries` dataset still contains UK.
From an already closed issues, #131 I understand that the `eu_countries` dataset reflects the data in [1] which doesn't list UK anymore.

The `eu_candidate_countries` is also incomplete: MD and UA are missing.

[1] https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Tutorial:Country_codes_and_protocol_order#Codes.2C_names_and_protocol_order_of_European_Union_.28EU.29_Member_States

**Comment by antagomir** [comment]
Good point. 

We should take this into account with the next update, which hopefully can take place soon.

**Comment by antagomir** [comment]
PRs also welcome.

**Comment by espinielli** [comment]
> PRs also welcome.

See #246
