### ISSUE TITLE
Server connection issue

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/eurostat#250]
### Discussed in https://github.com/rOpenGov/eurostat/discussions/249

<div type='discussions-op-text'>

<sup>Originally posted by **barry-coleman-lp** January 19, 2023</sup>
Hello,

Firstly, thank you for creating this package. I am a huge fan.

I have run in to an issue today where I can no longer access the server using the R package.

I cannot find any resources online to help with this issue and I'm looking for some help.

`> get_eurostat_toc()`
`Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  InternetOpenUrl failed: 'A connection with the server could not be established'`</div>

**Comment by barry-coleman-lp** [comment]
Thanks @pitkant.

I think this may be due to my connection or proxy settings. I will review and share any updates.

I tested the package and connection in the R-Studio cloud and it is working fine.

**Comment by pitkant** [comment]
Thank you for your follow-up @barry-coleman-lp . I tested the package as well and the connection worked fine. Connection problems related to proxy settings are a common source of problems.
