### ISSUE TITLE
Fix cran error

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#26]
In vignette. Due to, I think, eurostat change.

**Comment by jhuovari** [comment]
Less fragile way would be to include downloaded table with package and use that with vignette. Eurostat keeps changing their tables now and then.

But with this fix ready to upload.

**Comment by antagomir** [comment]
Great, thanks ! I checked all and submitted to CRAN (btw if someone ever needs the submission can be done with devtools::release() but then one also needs to modify the ./cran-comments.md file.)
