### ISSUE TITLE
get_eurostat

### ISSUE THREAD

**Issue by dw006** [rOpenGov/eurostat#27]
When using get_eurostat I receive an error. The search for the id as well as the download works. But  assigning the data to the data.frame gives an error. 

    id <- search_eurostat("Modal split of passenger transport", 
                      type = "table")$code[1]
    print(id)
[1] "tsdtr210"
    
    dat <- get_eurostat(id, time_format = "num")

Error in `$<-.data.frame`(`*tmp*`, "values", value = numeric(0)) :
Replacement has 0 rows, data has 2145

Any help is appreciated!

**Comment by antagomir** [comment]
Thanks for the report ! For some reason I am not able to reproduce your bug. The command
      library(eurostat); dat <- get_eurostat("tsdtr210", time_format = "num")
is successful.

Can you check with our latest devel version which you can install with 
devtools::install_github("ropengov/eurostat")

and let us know if the issue still persists ?

**Comment by dw006** [comment]
Yes, the problem persists. 
But as far as I could track it down, it comes from library(reshape). Without loading that package all works well. After loading get_eurostat() is brocken.

**Comment by jhuovari** [comment]
It is indeed the `reshape`.
It seems that it is an issue on reshape2:
https://github.com/hadley/reshape/issues/63
that affects also tidyr: https://github.com/hadley/tidyr/issues/29 
I will comment on those issues.

For quick fix my recommend is to use `reshape2` instead of `reshape`, or better still `tidyr`.

**Comment by jhuovari** [comment]
The latest devel version should now work also with reshape attach.
