### ISSUE TITLE
eurostat stopped working with 410 (gone error)

### ISSUE THREAD

**Issue by hrpunio** [rOpenGov/eurostat#289]
Version 4.0
https://wikis.ec.europa.eu/display/EUROSTATHELP/API+-+Migrating+from+Bulk+Download+Listing+urls+to+API+urls

**Comment by pitkant** [comment]
Thank you for opening this issue @hrpunio

What was the code you used when you got this error? Dataset ID and other parameters / arguments

**Comment by hrpunio** [comment]
Sorry for false alarm. I have upgraded eurostat to 4.0 but did not restart RStudio.
Probably it was the cause of problems.
I checked with sessionInfo() and it was 4.0 so I was sure I am using the latest one, but downloading URL was still invalid. 
Today it (eurostat) uses https://ec.europa.eu/eurostat/api/dissemination/sdmx/
and everything works...
Thanks

**Comment by pitkant** [comment]
No problem, good to hear that everything works now. Don't hesitate to open a new issue if you encounter any other problems.
