### ISSUE TITLE
Use read_tsv from readr instead of read.table

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#29]
Tested new `readr` package to read the tsv file. It is somewhat faster, but the difference is not a big. If implemented, should change also the `tidy_eurostat()` 

tested:
```
id <- "avia_goincc"
base <- eurostat_url()		   
url <- paste(base, 
             "estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2F",
             id, ".tsv.gz", sep="")

tfile <- tempfile(fileext = ".tsv.gz")
# download and read file
download.file(url, tfile)

# Present:
system.time(dat1 <- read.table(gzfile(tfile), sep="\t", na.strings = ": ", 
                                header = TRUE, stringsAsFactors = FALSE))
#   user  system elapsed 
#  1.23    0.00    1.25 

# with readr:
system.time({
  n <- ncol(readr::read_tsv(tfile, n_max = 1))
  dat2 <- readr::read_tsv(tfile, na = ": ", 
                          col_types = c(list(readr::col_character()),
                                        rep(list(readr::col_numeric()), 
                                            times = n-1)))
  })
#    user  system elapsed 
#   0.94    0.00    0.93 
unlink(tfile)
```

**Comment by briatte** [comment]
Two quick notes based on trying to use `readr` in a few projects over the past months:

- `readr` is really sensitive with dates: a column containing `2005-01`, `2005-02`, etc. can easily get converted to `NA` (with a warning that there were problems). This was fixed [just a few days ago](https://github.com/hadley/readr/issues/228).
- `readr` still has trouble dealing with some encoding configurations (there's quite a few issues about that on the repo). [It's also getting better in the past few days](https://github.com/hadley/readr/issues/40).

I'm underlining these issues just to say that it might be a good idea to integrate `readr` (which I like very much) only from the next release onwards.

In my limited experience, the speed difference is quite remarkable when the file size gets close or above 100 MB, which is not that uncommon for Eurostat data.

**Comment by jhuovari** [comment]
I agree!

**Comment by pbiecek** [comment]
read_tsv returns tibble now,
so this change will solve #52 as well

**Comment by pbiecek** [comment]
IMHO it's a good idea to switch to read_tsv/tibble,
However this may break some code since tibble is not 100% compatible with data.frame
Since it will be a global change I would change the version to 2.0
And maybe this update will be a good excuse to finish the RJournal submission.

@jhuovari @antagomir what do you think?

**Comment by antagomir** [comment]
I fully agree. In fact, we were just working with Markus to finalize the remaining RJournal points now after the summer vacations. I am almost to submit. But let's indeed implement the tibble everywhere and update version to 2.0 before submission. If you could give a touch on tibble, I am meanwhile finalizing the manuscript material and taking care of the submission unless there are other suggestions.

**Comment by pbiecek** [comment]
Great, sounds like a plan.

read_tsv is introduced in 3fee50ed8a1477e52f9eae9a0641cadc0a6a700c

Bu default all columns are read as characters to avoid problems with flags.
