### ISSUE TITLE
ert_bil_eur_d dataset does not seem to work

### ISSUE THREAD

**Issue by rideofyourlife** [rOpenGov/eurostat#300]
As below:
![image](https://github.com/rOpenGov/eurostat/assets/81742568/96906bd8-db39-49b9-b02e-e6c6705fb920)

**Comment by pitkant** [comment]
Thank you for the report. It seems to be related to `readr` package / `vroom` as I got the following error message while debugging `get_eurostat_raw()`:

```
readr::read_tsv(gzfile(tfile), na = ":", progress = TRUE, 
+                 col_types = readr::cols(.default = readr::col_character()))
Error: The size of the connection buffer (131072) was not large enough
to fit a complete line:
  * Increase it by setting `Sys.setenv("VROOM_CONNECTION_SIZE")`
```

There are several reports of a similar error message from 2021 and 2022 and I am not sure what causes it and why this happens with this specific dataset. I was able to download the data when I set the parameter `use.data.table = TRUE`:

```
avg <- get_eurostat("ert_bil_eur_d", use.data.table = TRUE)
```

As a temporary solution, does this work for you?
