### ISSUE TITLE
Error cannot open the connection

### ISSUE THREAD

**Issue by jlprol** [rOpenGov/eurostat#305]
When doing exactly what the tutorial says

```
library(devtools)
devtools::install_github("ropengov/eurostat")
library(eurostat)
passengers <- search_eurostat("passenger transport")
```
I get the following error:

```
Error in open.connection(4L, "rb") : 
  cannot open the connection to 'https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=table_of_contents_en.txt'
In addition: Warning message:
In open.connection(4L, "rb") :
  cannot open URL 'https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=table_of_contents_en.txt': HTTP status was '410 Gone'
```

**Comment by pitkant** [comment]
Thank you for opening an issue. It seems you are currently using an older version of the eurostat package. I suggest you update it to the newest available version on CRAN.

**Comment by jlprol** [comment]
I thought installing from github would get me the latest version. But indeed installing from CRAN solves the issue, thank you.

**Comment by jlprol** [comment]
I thought installing from github would get me the latest version. But indeed installing from CRAN solves the issue, thank you.

**Comment by pitkant** [comment]
Yes, it's curious. When no branch is specified it should install from master/main branch which is in this case effectively the same as the latest CRAN release. I usually use remotes::install_github nowadays so I will have to check how devtools equivalent works (and update the tutorial). Thanks for catching this
