### ISSUE TITLE
replace plyr with dplyr

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#31]
This will be useful for many compatibility issues as plyr and dplyr are poorly compatible, and dplyr is now rapidly becoming more popular.

**Comment by jhuovari** [comment]
I strongly agree on principle, but I think plyr is only used for mapvalues in label_eurostat and there are no replacement for that in dplyr.

Also, plyr is not attached by eurostat and mapvalues is called with plyr::mapvalues, so there shouldn't be problems. (Even if, after reshape issue I am not anymore totally sure of that.)

18.4.2015 22.19 kirjoitti Leo Lahti <notifications@github.com>:

This will be useful for many compatibility issues as plyr and dplyr are poorly compatible, and dplyr is now rapidly becoming more popular.

**Comment by antagomir** [comment]
I agree this is not urgent. Compatibilty issues exist, though, and are frequently encountered. Perhaps there will be progress in the near future. Perhaps good to wait and see.

**Comment by jhuovari** [comment]
We could however get rid of mapvalues and plyr all together. That would not be hard. One less dependency.

18.4.2015 22.19 kirjoitti Leo Lahti <notifications@github.com>:

This will be useful for many compatibility issues as plyr and dplyr are poorly compatible, and dplyr is now rapidly becoming more popular.
