### ISSUE TITLE
Add option stringsasfactors=FALSE to get_eurostat()

### ISSUE THREAD

**Issue by altomani** [rOpenGov/eurostat#34]

**Comment by jhuovari** [comment]
Good idea. I will add.

**Comment by antagomir** [comment]
should it be stringsAsFactors as in read.csv

**Comment by jhuovari** [comment]
Yes, planing to use: `stringsAsFactors = default.stringsAsFactors()`.

**Comment by jhuovari** [comment]
On master now, please test.

**Comment by antagomir** [comment]
Works perfect.

**Comment by altomani** [comment]
Works very well for me too.
