### ISSUE TITLE
Reorder factors based on dictionary

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#35]
Some variables, like classifications, have logical or at least conventional ordering. Eurostat data tables does not seems to have this ordering, but dictionaries seems to have. `label_eurostat()` could be modified to reorder factor levels in data to the order from dictionaries. Optionally?

**Comment by antagomir** [comment]
I support the idea. But it should be optional. In my experience the user sometimes likes to keep her own ordering of the factor levels, so the reordering should not be forced. It can be a default, though.

**Comment by jhuovari** [comment]
Try `label_eurostat(get_eurostat("nama_aux_lp"), eu_order = TRUE)$geo[1:20]`.

eu_order = FALSE is default.
