### ISSUE TITLE
get_eurostat() does not handle daily data correctly

### ISSUE THREAD

**Issue by Struya** [rOpenGov/eurostat#36]
It seems that the workhorse function `eurostat::get_eurostat()` does not handle daily data correctly. It can convert dates only down to monthly frequency.

    library(eurostat)

    # Euro/ECU exchange rates - daily data
    id <- "ert_bil_eur_d"

    dat <- 
      get_eurostat(id, time_format = "raw")

    dat_date <-
      get_eurostat(id, time_format = "date", update_cache = TRUE)  

### dat: time_format = "raw"

    tbl_df(dat)
    Source: local data frame [379,584 x 5]

       statinfo unit currency       time  values
    1       AVG  NAC      ARS 2015M07D03 10.1028
    2       AVG  NAC      AUD 2015M07D03  1.4747
    3       AVG  NAC      BGN 2015M07D03  1.9558
    4       AVG  NAC      BRL 2015M07D03  3.4584
    5       AVG  NAC      CAD 2015M07D03  1.3961
    6       AVG  NAC      CHF 2015M07D03  1.0466
    7       AVG  NAC      CNY 2015M07D03  6.8856
    8       AVG  NAC      CZK 2015M07D03 27.1450
    9       AVG  NAC      DKK 2015M07D03  7.4607
    10      AVG  NAC      GBP 2015M07D03  0.7102

### dat_date: time_format = "date"

    tbl_df(dat_date)
    Source: local data frame [379,584 x 5]

       statinfo unit currency       time  values
    1       AVG  NAC      ARS 2015-07-01 10.1028
    2       AVG  NAC      AUD 2015-07-01  1.4747
    3       AVG  NAC      BGN 2015-07-01  1.9558
    4       AVG  NAC      BRL 2015-07-01  3.4584
    5       AVG  NAC      CAD 2015-07-01  1.3961
    6       AVG  NAC      CHF 2015-07-01  1.0466
    7       AVG  NAC      CNY 2015-07-01  6.8856
    8       AVG  NAC      CZK 2015-07-01 27.1450
    9       AVG  NAC      DKK 2015-07-01  7.4607
    10      AVG  NAC      GBP 2015-07-01  0.7102

### Session info

    devtools::session_info()
    Session info ---------------------------------------------------------------------------------------------------------------------
     setting  value                       
     version  R version 3.2.0 (2015-04-16)
     system   x86_64, mingw32             
     ui       RStudio (0.99.435)          
     language (EN)                        
     collate  Slovenian_Slovenia.1250     
     tz       Europe/Prague               
    
    Packages -------------------------------------------------------------------------------------------------------------------------
     package    * version date       source        
     assertthat   0.1     2013-12-06 CRAN (R 3.1.3)
     curl         0.9     2015-06-19 CRAN (R 3.2.1)
     DBI          0.3.1   2014-09-24 CRAN (R 3.1.3)
     devtools     1.8.0   2015-05-09 CRAN (R 3.2.0)
     digest       0.6.8   2014-12-31 CRAN (R 3.1.3)
     dplyr      * 0.4.2   2015-06-16 CRAN (R 3.2.1)
     eurostat   * 1.0.16  2015-03-27 CRAN (R 3.2.1)
     git2r        0.10.1  2015-05-07 CRAN (R 3.2.0)
     lazyeval     0.1.10  2015-01-02 CRAN (R 3.1.3)
     magrittr     1.5     2014-11-22 CRAN (R 3.1.3)
     memoise      0.2.1   2014-04-22 CRAN (R 3.1.3)
     plyr       * 1.8.3   2015-06-12 CRAN (R 3.2.1)
     R6           2.0.1   2014-10-29 CRAN (R 3.1.3)
     Rcpp         0.11.6  2015-05-01 CRAN (R 3.2.0)
     reshape2     1.4.1   2014-12-06 CRAN (R 3.1.3)
     rversions    1.0.1   2015-06-06 CRAN (R 3.2.0)
     stringi      0.5-5   2015-06-29 CRAN (R 3.2.1)
     stringr    * 1.0.0   2015-04-30 CRAN (R 3.2.0)
     tidyr        0.2.0   2014-12-05 CRAN (R 3.1.3)
     xml2         0.1.1   2015-06-02 CRAN (R 3.2.0)

**Comment by jhuovari** [comment]
You are right. I will fix soon.

**Comment by jhuovari** [comment]
Should work now on development version. Please test. Thank you for reporting.

**Comment by antagomir** [comment]
Thanks so much again @jhuovari

**Comment by Struya** [comment]
That was fast. It works on my machine.
