### ISSUE TITLE
Issue with negative values (being converted to absolute values)

### ISSUE THREAD

**Issue by Hergie** [rOpenGov/eurostat#38]
Hello,
Thank you so much for the very useful package! It's been a great help.

However, I encountered a problem when downloading eurostat series with negative values. In R these don't get recorded as negative but as positive (i.e. the absolute value).

This happened to me when downloading tables [nama_nace31_k] & [nama_nace21_k]. If you choose variable indic_na="B1G" & unit="PCH_PRE", i.e percentage change in gross value added, all the values are larger than 0. This is even though the volume series in levels exhibit also decreases from time to time.

What am I doing wrong or is there some kind of bug?

Many thanks!

**Comment by jhuovari** [comment]
Hi,

I don't seems to be able to replicate your problem. With:
```
library("eurostat")
dat <- get_eurostat("nama_nace31_k")
subset(dat, indic_na == "B1G" & unit == "PCH_PRE" & nace_r1 == "D" & geo == "FI")
```
I do get negative values.

Could your share your code with the problem, if you still have the issue with negative values?

**Comment by Hergie** [comment]
Thanks for your reply. This is quite strange. I get the problem even with your example.

Sligthly modified:

```
library("eurostat")
dat <- get_eurostat("nama_nace31_k")
sample<-subset(dat, indic_na == "B1G" & unit == "PCH_PRE" & nace_r1 == "D" & geo == "FI")
summary(sample$values)
```
The above code prints out:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.100   2.925   4.300   5.900   9.050  19.900      13 
```

So again no negative values.

I'm running R-Studio Version 0.98.1049 with R version 3.1.2 (2014-10-31).

**Comment by pbiecek** [comment]
I've got

```
summary(sample$values)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
-19.900   2.425   4.150   3.894   7.225  13.800      13 
```

Would you try to reinstall the eurostat package and try again?

```
install_github("rOpenGov/eurostat")
```

**Comment by Hergie** [comment]
Thanks pbiecek, now it works!

Previously I had downloaded the regular version of the eurostat package (1.0.16 from March?) with install.packages('eurostat') so maybe the issue lies there?

**Comment by jhuovari** [comment]
For me also 1.0.16 works fine. It could be some conflict with an other package. Could you still sent what other packages your were using. `sessionInfo()` gives you a list.

I would like to know what really was the problem.

**Comment by Hergie** [comment]
Hi jhuovari,
Sorry, I'm not sure how to retrospectively get the `sessionInfo()` given that I no longer encounter the problem. I'll try though!
