### ISSUE TITLE
Problem with label_eurostat

### ISSUE THREAD

**Issue by NiekOv** [rOpenGov/eurostat#39]
Hi everyone,

My colleague told me about this package for extracting data from eurostat and I really love it. Strangely enough though, there seems to be something wrong when I try to label a dataset. Even though I'm using the exact same code that my colleague shared with me (and for him it does work): 

toc <- get_eurostat_toc()

data_mar <- search_eurostat("Maritime", type = "dataset")

id <- "mar_go_qm_nl"
dat <- get_eurostat(id, time_format = "date")

datl <- label_eurostat(dat)

I was using R 3.2.0 and updated to 3.2.2 but it didn't matter. Does anyone know what the problem is? 

Best regards,
Niek

**Comment by jhuovari** [comment]
What actually seems to be wrong? For me it seems to work. Could you also include output of `sessionInfo()` together with a description of the problem?

**Comment by NiekOv** [comment]
Sorry, I suppose I wasn't very clear in my previous post. The problem is that my dataset is not actually labeled after using the label_eurostat function. The columns and variable names are still just numbered.

Here's my sessionInfo output:

R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] eurostat_1.0.16

loaded via a namespace (and not attached):
[1] plyr_1.8.3    magrittr_1.5  tools_3.2.2   Rcpp_0.12.0   stringi_0.5-5
[6] tidyr_0.3.0

**Comment by jhuovari** [comment]
Could you post what you get with:
`str(dat)` and `str(datl)`

**Comment by NiekOv** [comment]
These are my results:

![dat](https://cloud.githubusercontent.com/assets/14236461/9846347/eb8c83a0-5ad1-11e5-9bd8-a83757c8c9dd.jpg)
![datl](https://cloud.githubusercontent.com/assets/14236461/9846346/eb8bba10-5ad1-11e5-83f4-862dd1c03749.jpg)

**Comment by jhuovari** [comment]
Strange. The problem is not with `label_eurostat()` as dat already is wrong. Try what you get with:
```
datr <- eurostat:::get_eurostat_raw("mar_go_qm_nl")
head(datr[1:3])
```

**Comment by NiekOv** [comment]
Thanks for taking the time to help me. I get the following:

> head(datr[1:3])
  direct.cargo.unit.par_mar.rep_mar.time X2014Q4 X2014Q3
1                     IN,DBK,THS_T,AE,NL      NA      NA
2              IN,DBK,THS_T,AE,NL_0NL888      NA      NA
3              IN,DBK,THS_T,AE,NL_0NLRTM      NA      NA
4              IN,DBK,THS_T,AE,NL_0NLVLI      NA      NA
5                     IN,DBK,THS_T,AG,NL      NA      NA
6              IN,DBK,THS_T,AG,NL_0NLRTM      NA      NA

**Comment by jhuovari** [comment]
That's how it should be. Try to update your packages, so that you get tidyr to version 0.3.1.

**Comment by NiekOv** [comment]
That's the trick. Thanks a lot!

**Comment by jhuovari** [comment]
Great, it's solved. It was a bug in the tidyr 0.3.0 (#104).
