### ISSUE TITLE
ggplot2 dev

### ISSUE THREAD

**Issue by hadley** [rOpenGov/eurostat#42]
I see the following problems:

```
checking files in ‘vignettes’ ... NOTE
The following directory looks like a leftover from 'knitr':
  ‘figure’
Please remove from your package.
```

**Comment by pbiecek** [comment]
I do not see this NOTE 
Just * checking files in ‘vignettes’ ... OK

Which version is the ggplot2 dev?
Latest on https://github.com/hadley/ggplot2 is 1.0.1.9003

**Comment by hadley** [comment]
Yes, that's the dev version. That problem might have been from an old version of knitr.  There are more problems on the CRAN check page: https://cran.r-project.org/web/checks/check_results_eurostat.html

**Comment by antagomir** [comment]
Thanks for pointing this out. I also do not see the knitr warning any more. The other warnings in cran come from tightened checks regarding manpages (imports must be explicit now) and I just fixed those. We will submit an updated package to cran soon.
