### ISSUE TITLE
Eurostat JSON

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#43]
Eurostat have also API to get data in a JSON format. That is handy if you wan't just a part of a dataset, as you can filter the data before downloading.

This should not be a replacement for existing method, as there is a size limit for API calls, but an addition.  

Below is an quick demonstration to get JSON data:
```r
get_eurostat_json <- function(dataset, filters = NULL){
  url_list <- list(scheme = "http",
                        hostname = "ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en",
                        path = dataset,
                        query = filters)
  class(url_list) <- "url"
  url <- httr::build_url(url_list)
  jdat <- jsonlite::fromJSON(url)
  dims <- jdat[[1]]$dimension
  ids <- dims$id

  dims_list <- lapply(dims[rev(ids)], function(x){
    unlist(x$category$label)
  })
  
  variables <- expand.grid(dims_list, KEEP.OUT.ATTRS = FALSE)
  
  dat <- data.frame(variables[rev(names(variables))], values = jdat[[1]]$value)
  dat
}

y <- get_eurostat_json("cdh_e_fos")
yy <- get_eurostat_json("nama_gdp_c", filters = list(geo="EU28",
                                                     unit="EUR_HAB",
                                                     indic_na="B1GM")) 
```

**Comment by antagomir** [comment]
Imo we should at least mention this extension opportunity in the manuscript if no possible implement before submission.

**Comment by jhuovari** [comment]
Should we have a separate function for JSON or should it be integrated with `get_eurostat()`:
* if filtering argument used -> get_eurostat_JSON
* otherwise `get_eurostat_raw()` (a present bulk download facility)

**Comment by jhuovari** [comment]
I pushed a preliminary version to json branch: 443b4b8083ed0775e1fb111eeb555d20fd11bdaf

**Comment by antagomir** [comment]
I can't test the version right now but as a general comment, I prefer wrapping it directly with `get_eurostat()`, although it is possible to provide an additional, separate JSON function.

Leo

**Comment by antagomir** [comment]
Ok seems to work for me. 

I vote for using get_eurostat as a general wrapper which can call all versions (raw & json) as suggested above.

An example in the package vignette would be also useful, to keep the tutorial complete.

**Comment by jhuovari** [comment]
Yes, it would be nice to have one main function for both methods. I have though something like this:
* based on filters argument the method is chosen: NA = bulk, NULL or list() = json.
* `get_eurostat_json()` is also exported and extra functionality is documented there. Like ability to get variables in label -format. 
* All functionality can be accessed from `get_eurostat()` via ...-argument. 
* with default arguments and without filters `get_eurostat()` should return a same data.frame with both methods.
* `get_eurostat_json()` returns time in "raw" format. One should use `get_eurostat()` or manually `eurotime2date()` or `eurotime2num()` to get other time formats.
* The Eurostat API have limitation of 50 sub-indicators. The `get_eurostat_json()` should probably check. 

I think the `get_eurostat_json()` in json branch have now a basic functionality: 3bc2440c8d6c61c90e3a014405fff56be74a4356. Next the `get_eurostat()` should be modified.

**Comment by antagomir** [comment]
Sounds perfect to me.

**Comment by jhuovari** [comment]
I have now merged json to main branch. I should work now as intended. Please test. Vignette and article updates still to do.

**Comment by antagomir** [comment]
Thanks. Works for me except three warnings (I just pushed fixes to master). I noticed these by running the ./inst/extras/build.cran.sh on command line will make CRAN check which is somewhat different from the basic tests provided by the devtools package, and required to be ok before CRAN submission.

The vignette + article updates on this would still be very useful.

* checking Rd files ... WARNING
get_eurostat_json.Rd:35-37: First argument to \href must be verbatim URL
get_eurostat.Rd:77-79: First argument to \href must be verbatim URL
problems found in ‘get_eurostat_json.Rd’, ‘get_eurostat.Rd’
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'convert_time_col.Rd':
  ‘tidy_eruostat’

**Comment by jhuovari** [comment]
Thanks for fixing those warnings and linking wrong commit here.

**Comment by jhuovari** [comment]
I updated to the tutorial how to use filters and type arguments. type is now available also with bulk download facility.

**Comment by antagomir** [comment]
Tnx. Looks good. Tests ok. I fixed some minor typos.
