### ISSUE TITLE
Problem with dev tidyr

### ISSUE THREAD

**Issue by hadley** [rOpenGov/eurostat#44]
```
checking files in ‘vignettes’ ... NOTE
The following directory looks like a leftover from 'knitr':
  ‘figure’
Please remove from your package.
```
```
checking re-building of vignette outputs ... NOTE
Error in re-building vignettes:
  ...
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Ftsdtr210.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 4001 bytes
==================================================
downloaded 4001 bytes

Quitting from lines 92-93 (eurostat_tutorial.Rmd) 
Error: processing vignette 'eurostat_tutorial.Rmd' failed with diagnostics:
argument is of length zero
Execution halted

```
```
DONE
Status: 2 NOTEs
```

Could you please let me know if this is a bug in the dev version of tidyr?

**Comment by antagomir** [comment]
I updated to the latest tidyr dev version and ran build/check again. This did not solve the issue, neither adding vignettes/figure in .Rbuildignore. However I could solve the issue now by changing the default vignette figure directory by setting 'opts_chunk$set(fig.path="fig/")' in the beginning of the vignette Rmd file.

**Comment by hadley** [comment]
It looks like you haven't uploaded a fix to CRAN yet. Please do so ASAP as I've just submitted tidyr.

**Comment by antagomir** [comment]
Done, thanks !

**Comment by clemlaflemme** [comment]
I've got the same issue in my own package. It's not clear to me what I should do now to fix this NOTE. help please !

**Comment by antagomir** [comment]
I have solved this issue by resetting fig.path in [vignettes/eurostat_tutorial.Rmd](https://github.com/rOpenGov/eurostat/blob/master/vignettes/eurostat_tutorial.Rmd) 

```{r setup, include=FALSE}
# Global options
library(knitr)
opts_chunk$set(fig.path="fig/")
```

**Comment by clemlaflemme** [comment]
ok I had `opts_chunk$set(fig.path="figure/", cache.path="cache/"), what should I do for the second folder? But moreover, why do this fix make sense ?

**Comment by antagomir** [comment]
I simply removed the folder 'figure' and instead put all contents in folder 'fig'. This issue depends on tidyr, and cannot be changed by fixing the eurostat package. For some reason tidyr warns against using the 'figure' folder.

**Comment by clemlaflemme** [comment]
I got also this interesting solution on [SO](http://stackoverflow.com/questions/40744735/leftovers-from-knitr/40744812#40744812)

**Comment by antagomir** [comment]
Nice, thanks for the tip.
