### ISSUE TITLE
stringsAsFactors = FALSE does not affect time

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#45]
`tidy_eurostat(x, time_format = "raw", stringsAsFactors = FALSE)` returns time variable in factor format. Comes from row 77 where `gather_` converts to factors. It seems, however, that this behaviour will change in next release of tidyr (see: https://github.com/hadley/tidyr/issues/96). 

So, I leave it as it in now and let tidyr update take are of this. But, perhaps we should add a conversion of the time (raw) to factors after that?

**Comment by antagomir** [comment]
For dates this could be beneficial (assuming the factor levels then have correct temporal ordering). For years, numeric would be better but perhaps it gets confusing unless we use factors there as well.

**Comment by jhuovari** [comment]
One can use time_format = "num" for numeric. I think "raw" should be factor or character. And, as it have been factor as default, probably best to retain that way. So factor conversion should be added before tidyr update.

**Comment by jhuovari** [comment]
I think updating tidyr to 0.4.0 will break our package. `time` column is no longer converted to factor and time column conversion will depend on it. With that commit the issue is fixed.
