### ISSUE TITLE
get_eurostat() drop units with all observations NA

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#46]
The `get_eurostat()` seems drop those variable combinations where all time observations are NA. 
Noticed that with `get_eurostat_json()`:
```
> dim(get_eurostat_json("cdh_e_fos"))
[1] 672   6
> dim(get_eurostat("cdh_e_fos"))
[1] 400   6
```
Should we fix it? Or leave as it is? In practise probably do not matter that much. And factors have all levels anyway. However, if we use `get_eurostat()` as a general wrapper, it should return same data.frame both ways.

**Comment by antagomir** [comment]
I would prefer keeping all data (not dropping NAs), and perhaps provide an extra function argument that can be used to drop variables where all times are NA. But I agree that in practice this may have limited relevance therefore not a top priority.

**Comment by jhuovari** [comment]
It was Eurostat that did the dropping. Datasets from the bulk download do not include all-NA observations. But in data from json API they are included. I think I will leave it that way. It means that `get_eurostat(id)` and `get_eurostat(id, filters = NULL)` do not return identical data.frames, as I intended in #43.

**Comment by antagomir** [comment]
Fine with me to leave it that way. But it would be good to have examples on both json and raw data versions in the vignette. The examples can use the same data set that returns non-identical outputs for the two functions. The reason can then be mentioned there.
