### ISSUE TITLE
Errors after `eurostat` package updates

### ISSUE THREAD

**Issue by BERENZ** [rOpenGov/eurostat#47]
I have updated `eurostat` package to version 1.2.13 on R 3.2.2. In result, I am not able to read into R tables that I have selected. Please find below two type errors that I have got and sessionInfo.

```
> eurostat::get_eurostat('isoc_cimobi_dev')
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fisoc_cimobi_dev.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 471305 bytes (460 KB)
==================================================
downloaded 460 KB

Error in if (tcode != "_" && nchar(times[1]) > 7) { : 
  missing value where TRUE/FALSE needed
> eurostat::get_eurostat('isoc_cias_mph')
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fisoc_cias_mph.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 46481 bytes (45 KB)
==================================================
downloaded 45 KB

Error in tidy_eurostat(y_raw, time_format, select_time, stringsAsFactors = stringsAsFactors,  : 
  Data includes several time frequencies. Select frequency with
         select_time or use time_format = "raw".
         Available frequencies: 'Y'''
```

```
> devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin14.5.0        
 ui       RStudio (0.99.862)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2016-01-22                  

Packages ----------------------------------------------------------------------------------
 package      * version date       source                               
 assertthat     0.1     2013-12-06 CRAN (R 3.2.0)                       
 curl           0.9.4   2015-11-20 CRAN (R 3.2.2)                       
 DBI            0.3.1   2014-09-24 CRAN (R 3.2.0)                       
 devtools       1.9.1   2015-09-11 CRAN (R 3.2.0)                       
 digest         0.6.9   2016-01-08 CRAN (R 3.2.2)                       
 dplyr        * 0.4.3   2015-09-01 CRAN (R 3.2.0)                       
 eurostat     * 1.2.13  2016-01-19 CRAN (R 3.2.2)                       
 httr           1.0.0   2015-06-25 CRAN (R 3.2.0)                       
 knitr          1.12    2016-01-07 CRAN (R 3.2.2)                       
 lazyeval       0.1.10  2015-01-02 CRAN (R 3.2.0)                       
 magrittr       1.5     2014-11-22 CRAN (R 3.2.0)                       
 memoise        0.2.1   2014-04-22 CRAN (R 3.2.0)                       
 PISA2012lite * 1.0     2016-01-22 Github (pbiecek/PISA2012lite@1616df2)
 R6             2.1.1   2015-08-19 CRAN (R 3.2.0)                       
 Rcpp           0.12.3  2016-01-10 CRAN (R 3.2.2)                       
 Rpoppler     * 0.0-1   2015-07-03 CRAN (R 3.2.2)                       
 SDaA         * 0.1-3   2014-09-04 CRAN (R 3.2.0)                       
 stringi        1.0-1   2015-10-22 CRAN (R 3.2.2)                       
 stringr        1.0.0   2015-04-30 CRAN (R 3.2.0)                       
 tidyr          0.4.0   2016-01-18 CRAN (R 3.2.2)    
```

**Comment by pbiecek** [comment]
Would you check the GitHub version of eurostat?
I have this error with CRAN version of eurostat,
but with GitHub version everything is working.

**Comment by jhuovari** [comment]
This is due to change in tidyr 0.4.0. It is fixed in commit that fixed #45. But unfortunately the cran  version does have the issue.

**Comment by antagomir** [comment]
To install the github devel version, use:
library(devtools)
install_github("ropengov/eurostat")

We will submit the next CRAN release within 1-2 months I guess.

**Comment by BERENZ** [comment]
Ok! it is working with github version, thanks!

**Comment by jhuovari** [comment]
I think we could try to release sooner as this issue will break the package for everyone. Also the json is now implemented and documented. 

We probably should also have tests that are run on cran. That way we would have avoided this.

**Comment by antagomir** [comment]
We can try to release sooner but CRAN instruction is that there should be about one month delay between updates. So we better wait for some time still to keep the admins happy and cooperative.

The CRAN tests are a mystery. I have seen some people asking around on how they test the packages but there was no clear answer. If someone can point out how, then let's implement. Otherwise the build/check with --as-cran option should do.

**Comment by pbiecek** [comment]
I thought that tests generated with testthat are executed during R CMD check (http://r-pkgs.had.co.nz/tests.html).
So maybe it's enough to remove 'skip_on_cran()'  from current tests?

**Comment by antagomir** [comment]
Not sure but isn't it so that testthat only runs the tests from the tests/ directory? We can remove skip_on_cran() from some of those but this does not solve all issues. The R CMD check --as-cran also has to pass fully before CRAN submission, and this tests also [many other aspects of a package](http://r-pkgs.had.co.nz/check.html). Yet it does not test everything tested by CRAN crew since our previous bug passed the R CMD check --as-cran, otherwise I could not have submitted. And the extra tests by CRAN crew remain a mystery to me at least for now.

**Comment by Stefan2015-5** [comment]
news on this would be great?

**Comment by antagomir** [comment]
Ok I just submitted the latest version to CRAN. I will put a not here when it's accepted.

**Comment by antagomir** [comment]
Ok the latest version is in CRAN now.

**Comment by Stefan2015-5** [comment]
many thanks!
