### ISSUE TITLE
Arguments "filters" and "type" do not appear when using get_eurostat()

### ISSUE THREAD

**Issue by jrs477** [rOpenGov/eurostat#48]
Hi,

I am trying to use the function get_eurostat(); however, when I try to pass the arguments "type" and/or "filters", I get errors.

For example: 
Error in get_eurostat(id, filters = list(geo = c("EU28", "FI"), lastTimePeriod = 1),  : 
  unused arguments (filters = list(geo = c("EU28", "FI"), lastTimePeriod = 1), type = "label")

AND

Error in get_eurostat(id, filters = list(geo = c("EU28", "FI"), lastTimePeriod = 1),  : 
  unused arguments (filters = list(geo = c("EU28", "FI"), lastTimePeriod = 1), type = "label")

Any ideas what's going on?
Apologies if this is a rookie mistake. I am still a novice at R.

Thanks!

~J

**Comment by jhuovari** [comment]
Hi,

Filters and type argument are not yet working in CRAN version of the package. What version of the eurostat-package are you using? To get the latest development version try:
```
library(devtools)
install_github("ropengov/eurostat")
```
If you still get an error, please report back.

**Comment by jrs477** [comment]
Thanks! It worked. 

How would I use the filters argument to exclude only a few countries (i.e., geo != c("EU15", "EU25", "EU28")) from my dataframe acquire by get_eurostat()?

Make sense?

**Comment by jhuovari** [comment]
Good,

With filter argument in eurostat you can only include. To exclude, get data without geo-filter and exclude afterwards with for example `subset(data, !(geo %in% c("EU15", "EU25", "EU28")))`. Note, to use codes in subsetting you should get data with `type = "code"`.
