### ISSUE TITLE
Switch to data_frames

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#52]
The data_frame format of the tibble package is useful update to data.frame: https://blog.rstudio.org/2016/03/24/tibble-1-0-0/ It could be useful to switch the output formats from data.frame to data_frame.

**Comment by pbiecek** [comment]
eurostat table TOC and searches are now in the tibble format, fixed in ece6de3b84fbf8983fdee6af2a45bd4e0fe1eefd
