### ISSUE TITLE
memory use

### ISSUE THREAD

**Issue by mrmvergeer** [rOpenGov/eurostat#53]
downloading a 4.2mb datafile, the package takes a long time, consumes all of the available (16Gb) memory. Tested with R 3.2.5 and 3.3.0 within R studio.
Code:
library(eurostat)
search_eurostat("asylum")
df1 <- get_eurostat("migr_asyappctzm")

**Comment by antagomir** [comment]
Thanks for reporting. Pull requests welcome, or we will have a look as soon as there is a chance.

**Comment by antagomir** [comment]
Should work now.
