### ISSUE TITLE
Exceptions to ISO 3166-1 alpha-2 

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#54]
There is an issue in your demo file and this has to be also considered in the context of package "countrycode"  and "eurostat". The European Commission and the Eurostat generally uses ISO 3166-1 alpha-2 codes with two exceptions: EL (not GR) is used to represent Greece, and UK (not GB) is used to represent the United Kingdom.

These exceptions basically touch upon any Eurostat tables. I think this special issue should be addressed either in eurostat or in countrycode, but I think this is not a universal issue, so is should be used in packages concerning European Commission / Eurostat data access.

While the issue is very simple to handle in program code, it is not very easy to detect. It took me quiet some time to find out about this, as I kept loosing some data values.

**Comment by antagomir** [comment]
Thanks a lot for the report. We are currently very busy with other tasks but will come back to this as soon as possible. Meanwhile, pull requests also welcome.

**Comment by antagomir** [comment]
Ok I added now an internal function harmonize_country_codes to convert all codes to the  ISO 3166-1 alpha-2 standard with GR for Greece and GB for United Kingdom. We may need to reconsider this after gathering some more experience. All feedback on this decision is welcome.

**Comment by antaldaniel** [comment]
Excellent, and sorry for not taking your invitation. I do a lot of R work, but I am not familiar with packages and GitHub. But I really like your work, and I think that I could add to it, so I'll catch up soon.

**Comment by antagomir** [comment]
Great, this is a real community effort and we most developers in fact never met each other irl but just here. Support is very welcome.

**Comment by jhuovari** [comment]
I think, by default the `get_eurostat` should return data as it is on Eurostat database, including codes. It is an official EU policy to use EL and UK, and I don't think we should chance codes. Also, if you use Eurostat web to search for codes, now they don't correspond to the `get_eurostat` output.

It would be better to have the `harmonize_country_code` as an separate function to those who wants to change codes. There could also be other similar helper functions. For example "Germany (until 1990 former territory of the FRG)"  and "Euro area (EA11-2000, EA12-2006, EA13-2007, EA15-2008, EA16-2010, EA17-2013, EA18-2014, EA19)" are not usually very handy geo names.

**Comment by antagomir** [comment]
I agree with jhuovari. We can change this as soon as someone has the chance to implement the required changes.
