### ISSUE TITLE
get_eurostat

### ISSUE THREAD

**Issue by dormirdebout** [rOpenGov/eurostat#56]
Hello,

When I use get_eurostat, I get the following memory problem :

> dat4 <- get_eurostat("bop_c6_q", select_time="Q")
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fbop_c6_q.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 36153672 bytes (34.5 MB)
downloaded 34.5 MB
Error: cannot allocate vector of size 396.9 Mb

So I have tried using the filter but it doesn't work either : 

> dat5 <- get_eurostat("bop_c6_q", select_time="Q", time_format = "num", filters = list(currency="MIO_EUR", bop_item="FA", sector10="S1", sectpart="S1", stk_flow="NET", partner="WRL_REST", geo="FR"))
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
Failure to get data. Probably filters did not return any data
or data exceeded query size limitation. Status code: 500

Can you help me ?

Thank you very much

**Comment by antagomir** [comment]
Thanks ! Should work now.
