### ISSUE TITLE
extract_numeric() is deprecated

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#60]
... in tidyr 0.6.0. Should be replaced with `readr::parse_numeric()` or maybe just with `is.numeric`.

**Comment by pbiecek** [comment]
readr::parse_numeric() will add readr as dependency,
Will replace it by 'as.numeric(gsub("[^0-9.-]+", "", as.character(x)))' (as originally in extract_numeric)

**Comment by pbiecek** [comment]
solved in 3aec8db0bca8e47987e6b7f53a871ed944580990
