### ISSUE TITLE
label_eurostat() returns an error in windows with latest development version behind a proxy

### ISSUE THREAD

**Issue by muuankarski** [rOpenGov/eurostat#63]
Using the latest version from Github (2.1.0002) and running code

    library(eurostat)
    p <- eurostat::get_eurostat("tgs00026", time_format = "raw")
    p <- label_eurostat(p)

Returns ` Error in open.connection(con, "rb") : Couldn't connect to server`, whereas the same script works fine when using the CRAN version (1.2.24)

Any idea what could have caused this? Happens behind a corporate proxy.

-Markus

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252    LC_MONETARY=Finnish_Finland.1252
[4] LC_NUMERIC=C                     LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] eurostat_2.1.0002

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6        lattice_0.20-33    tidyr_0.6.0        class_7.3-14       assertthat_0.1    
 [6] grid_3.3.1         R6_2.1.3           jsonlite_1.0       magrittr_1.5       e1071_1.6-7       
[11] httr_1.2.1         stringi_1.1.1      curl_1.2           sp_1.2-3           RColorBrewer_1.1-2
[16] tools_3.3.1        stringr_1.1.0      readr_1.0.0        classInt_0.1-23    tibble_1.1      
```

**Comment by jhuovari** [comment]
Works fine for me, but I not behind a proxy.

`get_eurostat_raw()` uses  `download.file()` to download data, but `get_eurostat_dic()` used by `label_eurostat()` uses `readr::read_tsv` directly to read connection via internal of readr: `read_connection()`.
And that was changed lately. 

Might be a curl issue see: https://github.com/hadley/readr/issues/349.

**Comment by pbiecek** [comment]
Could you paste the output from traceback()?
And could you check if the 'p' is a valid 'tbl' after 'get_eurostat'?

**Comment by muuankarski** [comment]
@jhuovari right, it could be an readr and curl issue as this 

    readr::read_tsv("http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=dic%2Fen%2Fna_item.dic")
Returns an error whereas this:

    read.delim("http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=dic%2Fen%2Fna_item.dic")

works ok. Something in curl interfering with proxy...? Have tried [configuring proxy settings in Rstudio](http://stackoverflow.com/questions/33262480/rstudio-proxy-configuration-on-windows), but with poor results.

As to @pbiecek 

    library(eurostat)
    p <- eurostat::get_eurostat("tgs00026", time_format = "raw")
    class(p)
    # [1] "tbl_df"     "tbl"        "data.frame" "list"       "oldClass"   "vector"  

And the traceback from `p <- label_eurostat(p)` looks this:

     Error in open.connection(con, "rb") : Couldn't connect to server

```
8. open.connection(con, "rb") 
7. open(con, "rb") 
6. read_connection(file) 
5. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
    locale = locale, skip = skip, comment = comment, n_max = n_max, 
    guess_max = guess_max, progress = progress) 
4. readr::read_tsv(tname, col_names = c("code_name", "full_name"), 
    col_types = readr::cols(.default = readr::col_character())) at get_eurostat_dic.R#27
3. get_eurostat_dic(dic, lang = lang) at label_eurostat.R#47
2. label_eurostat(y[[i]], i, eu_order = eu_order, lang = lang) at label_eurostat.R#32
1. label_eurostat(p) 

```

What do you think?

**Comment by jhuovari** [comment]
Does readr::read_tsv(url("http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=dic%2Fen%2Fna_item.dic")) work?

We could use this to overcome the issue.

**Comment by muuankarski** [comment]
Yes, does work with follow message 

    i <- readr::read_tsv(url("http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=dic%2Fen%2Fna_item.dic"))


```
Parsed with column specification:
cols(
  B1GQ = col_character(),
  `Gross domestic product at market prices` = col_character()
)
```

    head(i)

```
# A tibble: 6 x 2
   B1GQ Gross domestic product at market prices
  <chr>                                   <chr>
1   B1G                      Value added, gross
2    P1                                  Output
3    P2                Intermediate consumption
4    P3           Final consumption expenditure
5   P31      Individual consumption expenditure
6   P32      Collective consumption expenditure

```

**Comment by jhuovari** [comment]
Could you check @muuankarski that it OK now.

**Comment by muuankarski** [comment]
@jhuovari works like a charm! Thanks!

**Comment by antagomir** [comment]
Thanks for all. So is this case closed & can I now proceed with the submission?

**Comment by jhuovari** [comment]
I would say yes, go on.

**Comment by muuankarski** [comment]
On my behalf, yes!

**Comment by muuankarski** [comment]
@jhuovari Added the same url() -hack for `set_eurostat_toc`-function, to work properly behind my proxy, and pushed it to master.. do you see any potential risks in here?

https://github.com/rOpenGov/eurostat/commit/54a78b66d6519d453eef7a9e4dc8e48bbee3d353

**Comment by jhuovari** [comment]
Not any that I could think of. Good.
