### ISSUE TITLE
Fix pattern matching in search_eurostat()

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/eurostat#64]
`pattern` argument for `search_eurostat()` is a regex pattern passed on to `grep()`, but function documentation is not clear on this. The following query:

```
LiveBirths <- search_eurostat("Live births (total) by NUTS 3 region")
```

Will return no matches because the parentheses need to be escaped:

```
LiveBirths <- search_eurostat("Live births \\(total\\) by NUTS 3 region")
```

Either documentation could be made more clear about this or [grep](https://github.com/rOpenGov/eurostat/blob/master/R/search_eurostat.R#L29) could be called with `fixed = TRUE` to treat the pattern as is. Would love to leave a PR, but not sure if something else is affected.

**Comment by antagomir** [comment]
@jlehtoma Thanks a lot. Please leave a PR if you can. As far as I can see, this should be safe.

**Comment by jlehtoma** [comment]
Cool, left a PR https://github.com/rOpenGov/eurostat/pull/65

**Comment by antagomir** [comment]
Super ! Tnx !
