### ISSUE TITLE
Ready-made lists of country codes: problem with Germany?

### ISSUE THREAD

**Issue by markus-gastinger** [rOpenGov/eurostat#67]
Hi,

Since I am brand new to Github (and only slightly more experienced with R) I am not even sure this is how to use the issues tab here. However, I may have run into an issue with the ready-made lists of country codes included in the package as in `eu_countries`, specifically with regard to Germany.

First, I pull the data from a data set I found interesting

`ds1 <- get_eurostat("migr_pop1ctz", type = "label", time_format = "num")`

Since this data set is quite huge (4.5 million rows), I wanted to narrow it down to, among other things, only EU member states using `eu_countries`

`ds1TMP <- ds1[ds1$time >= 1998 & 
                ds1$citizen %in% "Total" & 
                ds1$age %in% "Total" & 
                ds1$sex %in% "Total" & 
                ds1$geo %in% eu_countries$name , ]`

The problem is that in the resulting object `ds1TMP` data for Germany is missing. I think this is because the country name for Germany is not actually *Germany* but *Germany (until 1990 former territory of the FRG)*, as can be seen from

`unique(ds1$geo)`

Again, apologies if this does not belong here. Anyway, thanks for your great package!

All the best,
Markus

**Comment by jhuovari** [comment]
Thanks for pointing that out.

Germany (until 1990 former territory of the FRG) have irratated me when plotting and I have an intention to add a funtion to shorten that (and also some other geo names). That would also help to solve this issue. 

However, I don't think that this is something we have to fix in `eu_countries` or `get_eurostat`.

Meanwhile, I think using `grepl` instead `%in%` could solve your problem.
