### ISSUE TITLE
Cheatsheet for eurostat

### ISSUE THREAD

**Issue by pbiecek** [rOpenGov/eurostat#71]
What do you think about a one page summary of eurostat functions?
I've started a pdf file (in the attachment), feel free to suggest/add changes. 
The last column may be about geo codes/maps.

[eurostat_cheatsheet.pdf](https://github.com/rOpenGov/eurostat/files/819825/eurostat_cheatsheet.pdf)

**Comment by muuankarski** [comment]
I do like the idea! Could the following text be refined for the last column? Feel free to modify it.


There are three function to work with geospatial data from GISCO. `get_eurostat_geospatial()` returns preprocessed spatial data as sp-objects or as data frames. `merge_eurostat_geospatial()` both downloads and merges the geospatial data with a preloaded tabular data. `cut_to_classes()` is a wrapper for `cut()` -function and is used for categorizing data for maps with tidy labels.

Fetch and process data
```
library(eurostat)
library(dplyr)
library(ggplot2)
get_eurostat("demo_r_frate3", time_format = "raw", stringsAsFactors = FALSE)  %>%
  dplyr::filter(time == 2014) %>%
  dplyr::mutate(cat = cut_to_classes(values, n=7, decimals = 1)) %>%
  merge_eurostat_geodata(data=.,geocolumn="geo",
                         resolution = "20", output_class = "df", 
                         all_regions = FALSE) -> mapdata
```
Draw a map using ggplot2
```
ggplot(mapdata, aes(x=long,y=lat,group=group)) +
geom_polygon(aes(fill=cat),color="dim grey", size=.1) +
scale_fill_brewer(type = "div", palette = "RdYlGn", direction = 1) +
labs(title="Total fertility rate, by NUTS-3 regions, 2014",
     subtitle="Average number of live births per woman",
     fill="Total fertility rate (%)") + theme_light() +
coord_map(project="orthographic", xlim=c(-12,44), ylim=c(35,70))
```

**Comment by antagomir** [comment]
Fabulous! The main functions should be covered, and the examples should be as simple and short as possible. Figures are  nice but I would avoid having too many of them. I can't provide more input right now but will try to provide more suggestions to the next version. Is there a source code for this sheatsheet available - could it be included in the package repository, for instance in the vignettes/ folder? p.s. our submission is still in review..

**Comment by pbiecek** [comment]
@muuankarski Thanks for these materials. I've slightly simplified the R code to fit the limited space. The updated version is here: https://github.com/rOpenGov/eurostat/blob/master/vignettes/cheatsheet/eurostat_cheatsheet.pdf

**Comment by pbiecek** [comment]
@antagomir It may be hard to create a fully reproducible cheatsheet. I was using Adobe Illustrator which works directly wit *.ai and *.pdf files. Sources are here https://github.com/rOpenGov/eurostat/tree/master/vignettes/cheatsheet

RStudio created templates for cheatsheets. But they are using Keynote/PowerPoint.
https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/. It is as unreproducible as Illustrator. We can convert the ai file to pptx it this format is better.

**Comment by antagomir** [comment]
Ah yes, I see the point. LaTeX is one option, we made an example of a [reproducible poster](http://ropengov.github.io/r/poster/latex/sweave/tikz/2015/06/07/ICCSS/) earlier but this solution requires quite some manual tuning and might be an overkill here. Anyway the cheat sheet is a great idea even when not fully reproducible, let's just go for it. Always possible to make reproducible versions later if an opportunity arises.

**Comment by antagomir** [comment]
The updated cheat sheet is good as is. Small suggestions for improvement:
 1. The figures in column 2 could span the whole column width (similar to the last figure in column 3)
 2. The map colors are now not friendly for red-green color blinds and could be therefore changed

The get_eurostat function could have an argument to switch on the labeling, so that there would be no need to apply the separate label_eurostat function. I think we chose not to do that but can't recall the reason and wondering whether we really would like to keep it that way. In my opinion it could be handy, although potentially confusing. In practice it does not make much difference.

**Comment by pbiecek** [comment]
Good points. Updated in fe0baf3a42a03fea8a97bf0ab15383b7a97b0a06.

Regarding type="label" in get_eurostat(). It will be a better (shorter) example (the 'Add labels' would be removed then). The problem is that I have to fill up the first column, so a third snippet is needed.

**Comment by pbiecek** [comment]
Uploaded to https://www.rstudio.com/resources/cheatsheets/

**Comment by antagomir** [comment]
Excellent.

**Comment by muuankarski** [comment]
very nice indeed!

ma 13. maalisk. 2017 klo 22.09 Leo Lahti <notifications@github.com>
kirjoitti:
