### ISSUE TITLE
plotrix example in manuscript is cluttered

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#74]
Review feedback: ""The labels in the “triangle plot” are very cluttered. It is almost impossible to pick out country labels in the cluster of countries that use little hydro power and a lot of biofuel. I am not familiar with the package that produced this plot, but if it is possible to only label some countries or otherwise produce a less cluttered plot I think that would be helpful."

Any preferences how to solve this ? The possible changes should also be taken into account at least in the [manuscript  figure source file](https://github.com/rOpenGov/eurostat/blob/master/vignettes/2015-RJournal/lahti-huovari-kainu-biecek.Rmd), [manuscript tex file](https://github.com/rOpenGov/eurostat/blob/master/vignettes/2015-RJournal/lahti-huovari-kainu-biecek.tex) and when applicable, also in the [vignette](https://github.com/rOpenGov/eurostat/blob/master/vignettes/eurostat_tutorial.Rmd) and function documentation.

**Comment by pbiecek** [comment]
Two solutions come to my mind,
one is to select only few interesting countries (like 5?) and plot only these five,
other is to zoom a part of the triangle.
Will work on this today.

**Comment by pbiecek** [comment]
Or enlarge the triangle to fit whole column.
Then figure 2A may be moved to figure 1.

**Comment by antagomir** [comment]
Zooming part of the triangle does not appear an attractive option to me. One more solution is to show the names only for a few places of interest, while keeping all dots. I would perhaps prefer showing fewer points, or the names for only a few points. Enlargening the triangle could also be a solution yet I feel that a triangle spanning the whole column might be too large. But I could be ok with that as well if it seems to work.

**Comment by pbiecek** [comment]
The new triangle plot fits same space as the previous one
see figure 2B in  https://github.com/rOpenGov/eurostat/blob/bb43c98cab46784e4ce7f178c4570bd26f15b396/vignettes/2015-RJournal/RJwrapper.pdf

The R code is slightly more complicated but still fits in the appendix.

**Comment by antagomir** [comment]
Perfect, I think this is good. Just confirm when you're ready and I could proceed with the manuscript submission. Thanks a lot for the fast action.

**Comment by pbiecek** [comment]
Ok, I think it's ready. Following files are updated: figures source file, manuscript text file and vignette / png+pdf.

**Comment by antagomir** [comment]
Super. Tnx again.
