### ISSUE TITLE
Get an error when loading gov_10a_main

### ISSUE THREAD

**Issue by AndreasBraun2015** [rOpenGov/eurostat#79]
Hello Sir,

I am using your package eurostat and I really love it. 

For most datasets it is working perfectly, however, I get the following error if I try to load gov_10a_main:

dataset <- get_eurostat("gov_10a_main", time_format = "date", type="label")

Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [91] is duplicated

It there a way to fix this?

Many thanks!

**Comment by jhuovari** [comment]
You have to get the data without type="label". There seems to be duplicated labels for na_item variable. So your have to deal with dublicates and label manually. Or remove duplicates and use `label_eurostat()`

To see duplicates:
```
dic_df <- get_eurostat_dic("na_item")
dic_df[(duplicated(dic_df$full_name)),]
```

**Comment by antagomir** [comment]
Hmm.. should we add an informative warning for these cases in get_eurostat_dic , including advice on what to do (= fix manually) when no good automated solution exists ? Might help to avoid confusion and save time for the users.

**Comment by jhuovari** [comment]
Should we solve duplicated labels by:
1. `label_eurostat()` gives an error and an informative error message.
2. `label_eurostat()` modifies duplicated labels (for example adding [2]...) and gives an informative warning message.
3. in a case of duplicated, the `label_eurostat()` transforms a factor to a chararter and gives an informative warning message.

The error occures only with factor, but I think we should add warning also in case of characters.

**Comment by jhuovari** [comment]
I think, my preference would be:

- Default behavior:  an error and an informative error message.
- Parameter `duplicated` to `label_eurostat()`. options: modify duplicated labels or turn to characters. In both cases retain also a code.
- For characters: a warning ina  case of duplicates.

**Comment by antagomir** [comment]
Default could indeed be an error and informative error message, which also tells how to solve (= using the duplicated argument in label_eurostat). I do not support changing the type from factors to characters, that will break consistency.

**Comment by jhuovari** [comment]
I fixed this by adding a `fix_dublicated` argument for the `label_eurostat()`. With `TRUE` (defalt) it gives an error in all cases (before character vectors did pass) and a message. With `FALSE` it add a corresponding code as prefix for a label and gives a message.

Lets change, if someone have better ideas.

**Comment by jhuovari** [comment]
So, to solve issue in the opener:
```
dataset <- get_eurostat("gov_10a_main", time_format = "date")
dataset_lab <- label_eurostat(dataset, fix_duplicated = TRUE)
```
