### ISSUE TITLE
Add remaining shape files

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#81]
At the moment eurostat package has only NUTS2013 regions implemented.

The NUTS2013 regions are missing the resolution 3:1. This could be added.

Also the other [administrative boundaries from GISCO](http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units) could be added.

**Comment by muuankarski** [comment]
Missing resolution 1:3 million added for get_eurostat_geodata() added here:  https://github.com/rOpenGov/eurostat/commit/881cc6768efee9daa2c8bc77b6f16db4399bc449

Meaning all the following resolutions work now at differeent nuts levels (0,1,2,3)

```r
library(eurostat)
get_eurostat_geospatial(resolution = "60", nuts_level = 0) %>% select("geo") %>% plot()
get_eurostat_geospatial(resolution = "20", nuts_level = 0) %>% select("geo") %>% plot()
get_eurostat_geospatial(resolution = "10", nuts_level = 0) %>% select("geo") %>% plot()
get_eurostat_geospatial(resolution = "3",  nuts_level = 0) %>% select("geo") %>% plot()
get_eurostat_geospatial(resolution = "1",  nuts_level = 0) %>% select("geo") %>% plot()
```
