### ISSUE TITLE
Use tmap for mapping example in the vignette

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/eurostat#83]
In case adding yet another package in to the mix isn't an issue, using the excellent [`tmap`](https://github.com/mtennekes/tmap) package for the mapping examples might be worth while. It's not really up to `eurostat` to decide which packages are used for plotting/mapping, but clear examples always help! The main benefits I see are:

1. A lot clearer API for producing the map (although takes a little getting used to)
2. Proper CRS handling

The [current examples](https://ropengov.github.io/eurostat/articles/eurostat_tutorial.html#maps) in the vignette could be +- implemented as follows:

```r
library(dplyr)
library(eurostat)
library(sf)
library(tmap)

# Coerce to a sf object
df60 <- st_as_sf(get_eurostat_geospatial(output_class = "spdf", resolution = 60))

# Map example 1

euro_sf <- eurostat::get_eurostat("tgs00026", time_format = "raw") %>% 
  # subset to have only a single row per geo
  dplyr::filter(time == 2010, nchar(as.character(geo)) == 4) %>% 
  # categorise
  dplyr::mutate(cat = cut_to_classes(values, n = 5)) %>%
  # merge with the spatial data
  # NOTE! geo becomes character
  dplyr::inner_join(df60, ., by = c("NUTS_ID" = "geo")) %>% 
  # use a proper coordinate reference syste (CRS): epsg projection 3035 - etrs89 / etrs-laea
  sf::st_transform("+init=epsg:3035") 

# Use tmap for creating the map
data(Europe)
tm_shape(Europe) +
  tm_fill("lightgrey") +
  tm_shape(euro_sf) +
  tm_grid(labels.inside.frame = FALSE) +
  tm_polygons("cat", palette = "Oranges") +
  tm_format_Europe()
```
![map_example_1](https://cloud.githubusercontent.com/assets/525495/26115377/1ec401fc-3a60-11e7-8c86-10a4a192b5dc.png)

```r
# Map example 2

euro_sf2 <- get_eurostat("tgs00026", time_format = "raw") %>% 
  # subsetting to year 2005 and NUTS-3 level
  dplyr::filter(time == 2005, nchar(as.character(geo)) == 4, grepl("PL",geo)) %>% 
  # label the single geo column
  dplyr::mutate(label = label_eurostat(.)[["geo"]],
                cat = cut_to_classes(values)) %>% 
  dplyr::inner_join(df60, ., by = c("NUTS_ID" = "geo")) %>% 
  # use a proper coordinate reference syste (CRS): epsg projection 3035 - etrs89 / etrs-laea
  sf::st_transform("+init=epsg:3035") 

tm_shape(Europe) +
  tm_fill("lightgrey") +
  tm_shape(euro_sf2, is.master = TRUE) +
  tm_polygons("cat", palette = "Oranges", border.col = "white", title = "Disposable household\nincomes in 2005") + 
  tm_text("label") + 
  tm_format_Europe()
```
![map_example_2](https://cloud.githubusercontent.com/assets/525495/26115487/6745be70-3a60-11e7-8859-9161df6da546.png)

Labels aren't quite the same as in the vignette here, but you get the point.

**Comment by antagomir** [comment]
Thanks !!! I think we should definitely add this to the vignette as soon as the time allows. And PRs are also very welcome always if we get slow  \o/

**Comment by jlehtoma** [comment]
Cool, all the necessary code (except the labels in example 2) is above, I'll see if I can come up with a PR at some point.

**Comment by antagomir** [comment]
I now incorporated these into the vignette. 

The map1 example (chunk map1ex) gives an error "Error: Fill argument neither colors nor valid variable name(s)" - I could not immediately solve, and set this chunk to eval=FALSE in the vignette. Have to come back to this later unless anyone has a solution readily available..

**Comment by muuankarski** [comment]
Now implemented and works.
Code: https://github.com/rOpenGov/eurostat/blob/master/vignettes/eurostat_tutorial.Rmd#disposable-income-of-private-households-by-nuts-2-regions-at-160mln-resolution-using-tmap
Output: http://ropengov.github.io/eurostat/articles/eurostat_tutorial.html#disposable-income-of-private-households-by-nuts-2-regions-at-160mln-resolution-using-tmap
