### ISSUE TITLE
add code search to search_eurostat 

### ISSUE THREAD

**Issue by ynux** [rOpenGov/eurostat#86]
Improvement request: When using search_eurostat it for asylum data, we have the issue that for many relevant datasets, the word "asylum" doesn't appear (especially in the English version). We need three searches to get all datasets with code MIGR_ASY*.

see
https://github.com/muc-fluechtlingsrat/r-eurostat-refugees/blob/master/man/eurostat_asylum_data_sources.rmd

It would be great if there was a code prefix search.

**Comment by antagomir** [comment]
We still have to postpone this from the next cran release but pull requests always welcome!

**Comment by antagomir** [comment]
Are regular expressions sufficient here?

**Comment by pitkant** [comment]
Closed with the CRAN release of package version 4.0.0
