### ISSUE TITLE
Flag issue - discrepancy between R output and Eurostat Excels ?

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#87]
Received this by email: 

While I was producing a table it struck me that there might be an issue with the flags. 

R does not consider flags with more than one letter. If there are flags with two letters (for example “bu”) it only keeps the first letter in the table (for example  “b”) . This differs from the Excel download table in which both letters are kept.

**Example**

I produced a table for employment rates of 20-34 years old in ISCED 3-4 with a general education with a duration of 1-3 years (Table: edat_lfse_24 in the Eurostat data base).  I selected the countries SI and HR

After some treatment the output was as follows:

![tab1](https://cloud.githubusercontent.com/assets/1228382/26673581/b06e5c74-46bd-11e7-8eb9-4a7eadd72c06.png)

However with the same combination of characteristics the Excel download from the Eurostat-homepage gave the following results:

Employment rates of young people not in education and training by sex, educational attainment level and years since completion of highest level of education [edat_lfse_24]

DURATION From 1 to 3 years
ISCED11 Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - general
AGE From 20 to 34 years
SEX Total
UNIT Percentage

![tab2](https://cloud.githubusercontent.com/assets/1228382/26673664/0530a92e-46be-11e7-928f-8a4382af109d.png)

As you can see in the flags for 2014, the R output kept the first letter only (“b”) while the second letters (“c”, “u”) were cut. The homepage download kept both letters, however.

Is there an issue with the flags procedure in the Eurostat package?

**R code**

```
library(tidyr)
library(knitr)
library(eurostat)
library(xlsx)
library(reshape)
# TBL002 Employment rates of 20-34 aged ISCED 3-4 GEN vs VET
# by length of education
TBL002 <- get_eurostat("edat_lfse_24", type = "code", time_format = "num", keepFlags = TRUE)
TBL002 <- subset(TBL002,
                 ( geo=="SI" | geo=="HR")
                 & sex=="T" & time>=2014
                 & age=="Y20-34" & isced11=="ED3_4GEN"
                 & duration=="Y1-3" )
# Reshape
myvars<- c("geo",  "duration", "values", "time", "isced11", "age")
TBL002V <- TBL002[myvars]
TBL002V_wide <- spread(TBL002V,  time, values)
myvars<- c("geo",  "duration", "flags", "time", "isced11", "age")
TBL002F <- TBL002[myvars]
TBL002F_wide <- spread(TBL002F,  time, flags)
TBL002F_wide <- rename(TBL002F_wide, c("2014"="2014F"))
TBL002F_wide <- rename(TBL002F_wide, c("2015"="2015F"))
TBL002F_wide <- rename(TBL002F_wide, c("2016"="2016F"))
TBL002VF_wide <- merge(TBL002V_wide, TBL002F_wide,
                       by=c("geo", "duration", "isced11", "age"), all = TRUE)
View(TBL002VF_wide)
```

**Comment by antagomir** [comment]
Further email requests received regarding this issue. Good to solve fast when time allows. PRs & suggestions welcome !

**Comment by jhuovari** [comment]
This is easy to fix. Except, that Eurostat have a flag "n" for "not significant", but also a 0n for "less than half the final digit shown and different from real zero". See: http://ec.europa.eu/eurostat/data/database/information

With easy solution they will look the same. How we should express 0n zeros? And does anyone know dataset were they are present?

**Comment by antagomir** [comment]
I propose that we set these them to the same value, with an informative warning? This can be improved later if someone really needs the feature.

**Comment by jhuovari** [comment]
For flags it should work now. For "0n" zeros, it could work, but I don't know because I have not seen them. However, multiple flags are now strings, like "bu". "0n" zeros should be indicated as "0n" in flags column. "0n" and flag should be string like "0n u".

Please test.

**Comment by antagomir** [comment]
Could you recommend a reproducible test in tests/ , or in vignettes, or here ?

**Comment by jhuovari** [comment]
I did write a test in tests/ and tried that the case in this issue works. The problem is the "0n", as I have never encountered them. Have someone else?

**Comment by antagomir** [comment]
I haven't. Not sure how easy it is to scan all data to find these cases. A quick hack would be to add some random 0n's manually after reading the data (just for testing purposes). Or to ignore the 0n case in the tests until someone reports an issue.
