### ISSUE TITLE
ommited lines

### ISSUE THREAD

**Issue by imi01** [rOpenGov/eurostat#88]
There might be an issue with the data extraction in the eurostat package. The package seems to drop lines, when both the value and the flag columns are empty. This is problematic when producing and exporting tables, because the missing lines have to be manually added, after. It can also be important when merging tables. If lines are dropped the respective values from another table will not be merged into the first table. 

Here is an example: The table below shows an extraction as provided after the normal Excel download from the Eurostat homepage.

Source [educ_uoe_grad01]
UNIT	NR			
SEX	Total			
ISCED11	ED3			
				
GEO | AGE/TIME | 2014 | Flags and footnotes	| dropped
-----|-----------|-------|--------------------- | ---------
EU28 | TOTAL | : |   | 	x
EU28 | Y20-24	 | :	 |  	 |x 
EU28 | Y25-29	 | :	  |  | x
EL | TOTAL | 113,127 |  	 | 
EL | Y20-24 | 11,682	  |  | 
EL | Y25-29 | 3,873	 |  	 | 
IT | TOTAL	 | 536,638	  |  | 
IT | Y20-24 | :	 |  	 | x
IT | Y25-29 | : | 	 	 | x
				

The lines marked with an "x" in the manually added column "dropped" show combinations of characteristics which have missing values in the 2014 and flags columns. However, the lines are still provided in the downloaded Excel file. In contrast, when extracting the same combinations of characteristics with the eurostat package in R the marked lines were dropped entirely. See the following example from the view table in R:

unit| age| sex| isced11| time| geo| flags| values
----| ------| -----| ----| ---| ---| ----| -------
NR| TOTAL| T| ED3| 2014| EL| NA| 113127
NR| Y20-24| T| ED3| 2014| EL| NA| 11682
NR| Y25-29| T| ED3| 2014| EL| NA| 3873
NR| TOTAL| T| ED3| 2014| IT| NA| 536638

All values for the EU28 are omitted and the lines for Italy were dropped if both the value and flag column had missing values. To replicate the R-example please find the code below.

```
library(eurostat)
  TBL004 <- get_eurostat("educ_uoe_grad01", type = "code", time_format = "num", keepFlags = TRUE)
  TBL004all <- subset(TBL004, 
                      (geo=="IT"  |  geo=="EL" |  geo=="EU28")
                      & time==2014 & sex=="T" 
                      & (age=="Y20-24" | age=="Y25-29" | age=="TOTAL") 
                      & (isced11=="ED3"))
  
  View(TBL004all)
```

**Comment by jhuovari** [comment]
The eurostat csv-files do include totally missing values. That why they are missing. 
We could add them, `tidyr::complete()` could be used.
But would that break existing code? Add with extra parameter `complete = FALSE`?

**Comment by antagomir** [comment]
Keeping all entries would be more compatible with eurostat files and my first impression is that this could be the default solution. It might not even be necessary to provide an extra option to drop the empty entries as this can be easily done afterwards too. But indeed the change might break existing code, therefore adding extra parameter such as `complete = FALSE` at this point  could be a clean solution. Or perhaps it could be `complete = TRUE` by default, with an accompanying warning message that this was changed? Then some existing code might be broken but it could be easily fixed by changing this argument.

**Comment by imi01** [comment]
Could you provide an example code to demonstrate this?

**Comment by jhuovari** [comment]
Would this do what you want?`
```
TBL004_complete` <- tidyr::complete(TBL004, unit, age, sex, isced11, geo, flags, time)
```

**Comment by imi01** [comment]
Thank you for the example. However, the output from my code is still not identical with Eurostats.
My aim is to get a table that is identical with the Eurostat output. For example I used the table 
educ_uoe_grad01 with the following characteristics

TABLE 1
UNIT		Number		
AGE		Total		
SEX		Total		
ISCED11		Upper secondary education		
				
GEO/TIME	|	2014	|	Flags and footnotes
------------|----------|---------------------
European Union (28 countries)|		: |	|	
Greece |		113,127	|	|
Italy	|	 536,638	|	|


The entry for the EU28 is empty and has no flags.
With the code similar to the one in the beginning I get the following:

 ```
 library(eurostat)
  TBL004 <- get_eurostat("educ_uoe_grad01", type = "code", time_format = "num", keepFlags = TRUE)
  TBL004all <- subset(TBL004, 
                      (geo=="IT"  |  geo=="EL" |  geo=="EU28")
                      & time==2014 & sex=="T" 
                      & ( age=="TOTAL") 
                      & (isced11=="ED3"))
  View(TBL004all)
```
  
TABLE 2

Entry | unit| age | sex	 | isced11	| geo	| flags   |	time	| values	
------|-----|-----|-----|--------|------|-------|--------|----------
1	|NR		|TOTAL	|	T	|	ED3	| EL	|NA	|	2014	|	113127
2	|NR		|TOTAL	|	T	|	ED3	| IT	|NA	|	2014	|	536638

The EU28 entry is missing, here.
So I used the following syntax, which basically differs by inserting the tidyr in between


  ```
library(eurostat)
  TBL004 <- get_eurostat("educ_uoe_grad01", type = "code", time_format = "num", keepFlags = TRUE)
  TBL004_complete <- tidyr::complete(TBL004, unit, age, sex, isced11, geo, flags, time)
  TBL004all <- subset(TBL004_complete, 
                      (geo=="IT"  |  geo=="EL" |  geo=="EU28")
                      & time==2014 & sex=="T" 
                      & (age=="TOTAL") 
                      & (isced11=="ED3"))
    View(TBL004all)
```
  
  An I got:
  
  TABLE 3

 Entry  |  unit | age  |	sex |	isced11 | geo | flags | time | values		
--------|-----|------|-----|---------|-----|------|------|-----------	
  1	|	NR	|	TOTAL	|	T	|	ED3	|	IT	|	d	|	2014	|	NA
  2	|	NR	|	TOTAL	|	T	|	ED3	|	IT	|	z	|	2014	|	NA
  3	|	NR	|	TOTAL	|	T	|	ED3	|	IT	|	e	|	2014	|	NA
  4	|	NR	|	TOTAL	|	T	|	ED3	|	IT	|	NA	|	2014	|	536638
  5	|	NR	|	TOTAL	|	T	|	ED3	|	EL	|	d	|	2014	|	NA
  6	|	NR	|	TOTAL	|	T	|	ED3	|	EL	|	z	|	2014	|	NA
  7	|	NR	|	TOTAL	|	T	|	ED3	|	EL	|	e	|	2014	|	NA
  8	|	NR	|	TOTAL	|	T	|	ED3	|	EL	|	NA	|	2014	|	113127
  9	|	NR	|	TOTAL	|	T	|	ED3	|	EU28	|	d	|	2014	|	NA
  10	|	NR	|	TOTAL	|	T	|	ED3	|	EU28	|	z	|	2014	|	NA
  11	|	NR	|	TOTAL	|	T	|	ED3	|	EU28	|	e	|	2014	|	NA
  12	|	NR	|	TOTAL	|	T	|	ED3	|	EU28	|	NA	|	2014	|	NA

  
  
 Indeed, this table keeps the entries with both flags and values NA. That is what was missing so far. However, the table has also entries that are actually not existing. For instance the flags d, z and e do not exist in the corresponding Eurostat output table (see for example entries 1,2,3). 
Of course it is possible to drop entries with a flag and with NA values. However, the decision requires checking the Eurostat data base, because there are tables that correctly have missing values and a flag.  For instance, if the numbers are confidential (c) this sometimes occurs.  In this case the rows should remain in the table and the entries where both flags and values are NA should be deleted, instead. Even a mixed case is thinkable. This means if the table is unknown it cannot be decided if the flag=NA, values=NA combination should be deleted or the flag=has entry, values=NA combination. This has to be checked in the data base manually. It would be helpful if someone could provide a working code example that automatically replicates the Eurostat excel-table output.

**Comment by jhuovari** [comment]
You should drop the `flags` from my code. I don't know, if that will return what you want, but the `flags` was mistake.

Meanwhile, I don't think we should make missing values explicit by default. In many eurostat tables, there are lot of missing values, and making them explicit will increase the size of the returned data.frame considerable. However, implicit missing values should be at least documented.

**Comment by antagomir** [comment]
Ok a good point. Let us keep missing values by default. But, if possible, it would be useful to have the option to return the exactly same table that comes from Eurostat. 

Would be useful to hear from @imi01 what are the most crucial problems related to this discrepancy ? Is this critical or for convenience.

**Comment by imi01** [comment]
Many thanks for the tip! This seems to work. My opinion is that missing values should be retained by default, which means the “Eurostat output” should be the standard. A typical user scenario is to extract a table for a report or so. This requires presenting countries or categories with missing values as well. If you work with many tables and you have to add various lines manually this requires further control operations and is a potential source of errors. If not taken into account the current default might also have implications for merging different tables if a line is dropped in the first data. Regarding data in general I think missing values are not “no information”. Rather they inform on particular data availability, which might be of interest, too. Thus, I would regard the complete data (including the missing values) as the starting point for any data work and leave the decision to drop lines up to the analyst. From a user’s perspective it might be more plausible as well if a package tailored to a particular data source provides the full data and does not require an additional package to get them (tidyr e.g.). The fact that many tables have missing values is not necessarily a problem, here. A solution might be to add a condition in the `filters` argument of the `get_eurostat` command that restricts the download to non-missing values if desired.

**Comment by antagomir** [comment]
I agree in general that the output would be preferably the same from all sources. In the eurostat R package, however, we must balance this with the fact that the table sizes may become unfeasible as there are often huge amounts of non-informative missing values and filtering them out can simplify many other aspects. I am not yet sure what would be the most feasible solution. Further comments are very welcome here.

**Comment by imi01** [comment]
I think a solution would be to add a routine a command that might be called by a condition - something like "missings=keep/drop".  Actually, the current standard just says "missings=drop". This is not a problem if you know it. However, this is not mentioned explicitly so that users discover this only in the course of their data work. 
If the eurostat-package would allow users to decide whether they want to download all cases or only non-missing entries this would solve the issue even if the default remains "drop missings" in the future. I think the issue is just enabling the choice and making it explicit.
Another, option might be to add a chapter in the package description (something like "Reproducing Eurostat data base outputs"). You might explain the issue and demonstrate the solution with tidyr by example, there.

**Comment by jhuovari** [comment]
Output using `filters`, thus getting data with `get_eurostat_json`, differs from that without. It includes NAs for partially missing, but omits if totally missing. Below data for EU28 is omitted, but for IT missig age groups are included.

```
TBL004_json <- get_eurostat("educ_uoe_grad01", type = "code", time_format = "num", 
                       filters = list(geo = c("IT", "EL", "EU28"),
                                      sex = "T",
                                      age = c("Y20-24", "Y25-29", "TOTAL"),
                                      isced11 = "ED3",
                                      time = 2014))
```
So, having same output from all sources might be tricky. Definitely we should update help packages, but otherwise there might not be simple options.

**Comment by antagomir** [comment]
Can we have all three options available through a function argument? I would keep the fully filtered data as the default for now unless there are other arguments.

**Comment by jhuovari** [comment]
I would suggest, just to update the documentation. 
For totally missing, we can't do the completion, as we don't know of them from data.
And, as it is pretty easy to do with `tidyr::complete()`, I would leave that to users who needs it.

**Comment by antagomir** [comment]
Perfect. Would also help to keep the core functionality of the package simple and clear. This has to be added to documentation, though, so I am leaving this open for the eager ones to fix & close.
