### ISSUE TITLE
get_eurostat does not work as published in the onepager

### ISSUE THREAD

**Issue by mathiae** [rOpenGov/eurostat#89]
I tried to run the example at the top of the second column and it failed.

> t1 <- get_eurostat("tsdtr420", filters =
+         list(geo = c("UK", "FR", "PL", "ES", "PT")))
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  Failure to get data. Status code: 407

However the first example works (see below)
> dat <- get_eurostat(id="tsdtr420", time_format="num")
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Ftsdtr420.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 1313 bytes
downloaded 1313 bytes

Table tsdtr420 cached at C:\Users\mathiae\AppData\Local\Temp\1\Rtmpiepai0/eurostat/tsdtr420_num_code_TF.rds

**Comment by jhuovari** [comment]
For me it works just fine. The error code is related to proxy authentication, I think. Could it be, that it is your proxy service that is causing trouble?

**Comment by mathiae** [comment]
Thanks for your answer. I work behind a proxy that could give some trouble. What is strange for me is that the problem occurs with the call
t1 <- get_eurostat("tsdtr420", filters =  list(geo = c("UK", "FR", "PL", "ES", "PT")))

and not with the call 
dat <- get_eurostat(id="tsdtr420", time_format="num")
that run just fine.

**Comment by jhuovari** [comment]
I´m not sure what´s the problem, but those two calls are different. The later just downloads a file, while the first uses eurostat-api.

You could try, if you get an error with the following, filling your proxy url, port and if needed username and password. 
```
resp <- httr::GET("http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/tsdtr420?geo=UK&geo=FR&geo=PL&geo=ES&geo=PT",  
    use_proxy(url, port , username, password))
```

**Comment by mathiae** [comment]
I tried 

resp <- httr::GET("http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/tsdtr420?geo=UK&geo=FR&geo=PL&geo=ES&geo=PT",  
    use_proxy(url, port , username, password))

but it does not work the function does not support anymore use_proxy (apparently).

I tried to fix the proxy issue. The last call failed because it cannot connect to the server. No complain about the proxy.

> library("eurostat")
> query <- search_eurostat("road", type = "table")
> dat <- get_eurostat(id="tsdtr420", time_format="num")
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Ftsdtr420.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 1313 bytes
downloaded 1313 bytes

Table tsdtr420 cached at C:\Users\mathiae\AppData\Local\Temp\1\RtmpYBL7FF/eurostat/tsdtr420_num_code_TF.rds
> t1 <- get_eurostat("tsdtr420", filters = list(geo = c("UK", "FR", "PL", "ES", "PT")))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server
>
