### ISSUE TITLE
problem with label_eurostat(). Country code related?

### ISSUE THREAD

**Issue by pssguy** [rOpenGov/eurostat#90]
```
library(eurostat)
pop <- get_eurostat("nama_10r_3popgdp")
pop <- label_eurostat(pop, code="geo") # removing code parameter makes no difference
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [19] is duplicated
```

Not quite sure how to resolve this
```
levels(pop$geo)[19] # "BE10"
```

but looks like it may somehow relate to Netherlands??

The vignette example does not cause the same issue

**Comment by jhuovari** [comment]
This is a same issue as in #79.

The problem is that BE1 and BE10 have same label: Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest. And factors can't have duplicated levels.

At the moment you have to manually resolve this. For example removing one of regions, before labelling.

**Comment by jhuovari** [comment]
You can also turn pop$geo to a character vector before labelling. Then, labelled geo is also a character, and duplicated values won't give you an error any more.

**Comment by jhuovari** [comment]
The example in the opener should now work in the github version.

**Comment by pssguy** [comment]
Thanks. No error now with github version provided 'fix_duplicated = TRUE' argument is applied
