### ISSUE TITLE
Revise spatial data sources 

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#96]
why you not used directly the shapefiles and relied now on RDATA on your github account ? Was ESTAT infrastructure not efficient enough? Do you need another format ? We also provide GeoJSON/TopoJSON and PBF format at http://ec.europa.eu/eurostat/cache/GISCO/distribution/v1/.

**Comment by antagomir** [comment]
Related to #97

**Comment by muuankarski** [comment]
Data source was changed to http://ec.europa.eu/eurostat/cache/GISCO/distribution/v1/ in https://github.com/rOpenGov/eurostat/commit/57d16860b9f8f7c6f21886bdccb30fa005a8a7a0
