### ISSUE TITLE
eurostat geodata locally in the package ?

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#97]
We could have local versions of eurostat geodata (geojson files) in the package to allow working off-line. However in that case we should also provide a function that updates these data sets from the GISCO sources upon request.

**Comment by muuankarski** [comment]
Geospatial sf-object at 1:60 million resolution now included with the package. Implemented in: https://github.com/rOpenGov/eurostat/commit/028e0df369c9fcbf75a7c596438ff8eb1323133b See: https://github.com/rOpenGov/eurostat/blob/master/R/get_eurostat_geospatial.R#L147

Finer resolutions are fetched from: 
http://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/nuts-2013-files.html
