### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by sjgmr13** [rOpenGov/eurostat#99]
The following code works properly:

**t1 <- get_eurostat("tsdtr420")**

If I want to use filters, I get an error message:

**t1 <- get_eurostat("tsdtr420", filters =
                 list(geo = c("UK", "FR", "PL", "ES", "PT")))**

Error message:
**Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10015 milliseconds**

**Comment by antagomir** [comment]
Thanks! We received the same report from someone else recently. Until this is fixed, you can use a workaround:

```
library(eurostat)
library(dplyr)
t1 <- get_eurostat("tsdtr420") %>% filter(geo %in% c("UK", "FR", "PL", "ES", "PT"))

```

**Comment by sjgmr13** [comment]
Thanks for the quick response.

**Comment by jhuovari** [comment]
Does this happen every time you use the `filters` argument?

We tried to fix it in #89. I think it could be an proxy issue, but I am not sure. For me it works fine.

**Comment by sjgmr13** [comment]
Yes it does. Now I am behind a proxy. Sorry, I don't know much about computer networks.
Also I am using Rstudio on Windows (the Use Internet Explorer library/proxy for HTTP option is checked in the Global Options).
I tried to edit to my .Renviron file and insert the http_proxy, and http_proxy_user. After this I get the following error message:

**Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  Failure to get data. Status code: 407**

**Comment by sjgmr13** [comment]
Not sure if it is related, but (removed http_proxy/http_proxy_user from .Renviron)

**lp <- get_eurostat_geospatial(output_class = "spdf", resolution = "20")**

yields:
**...
Error in load(url(paste0("https://github.com/rOpenGov/eurostat_geodata/raw/master/rdata/NUTS_2013_",  : 
  cannot open the connection
In addition: Warning message:
In load(url(paste0("https://github.com/rOpenGov/eurostat_geodata/raw/master/rdata/NUTS_2013_",  :
  InternetOpenUrl failed: '**

**Comment by jhuovari** [comment]
Could you check if you can get thru the proxy with this, using your proxy url and port:
```
resp <- httr::GET("http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/tsdtr420?geo=UK", 
                  use_proxy(url = "212.47.242.12", port = 3128), verbose())
```
You can give also a username and password, if needed. I managed with this thru a free public pxoxy.

**Comment by sjgmr13** [comment]
After doing this I get the following message:

```
-> GET http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/tsdtr420?geo=UK HTTP/1.0
-> Host: ec.europa.eu
-> Proxy-Authorization: Basic c2F2b2x5OkdPcmlvdGFwbzg4QA==
-> User-Agent: libcurl/7.54.1 r-curl/2.8.1 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Proxy-Connection: Keep-Alive
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.0 200 OK
<- Date: Fri, 15 Sep 2017 09:01:10 GMT
<- Content-Length: 810
<- Content-Type: application/json;charset=UTF-8
<- Access-Control-Allow-Methods: GET, POST, OPTIONS
<- Access-Control-Allow-Origin: *
<- Vary: Accept-Encoding
<- Server: Europa
<- Content-Encoding: gzip
<- X-Cache: MISS from foo
<- X-Cache-Lookup: MISS from foo:bar
<- Via: 1.0 foo (squid)
<- Connection: keep-alive
<-
```

**Comment by jhuovari** [comment]
Did you get data?

**Comment by sjgmr13** [comment]
Yes.

`>resp
Response [http://ec.europa.eu/eurostat/wdds/rest/data/v1.1/json/en/tsdtr420?geo=UK]
  Date: 2017-09-15 09:06
  Status: 200
  Content-Type: application/json;charset=UTF-8
  Size: 1.66 kB`

**Comment by jhuovari** [comment]
Great! Thanks. Now we can use this solution for the `get_eurostat_json` .

**Comment by jhuovari** [comment]
Can this be solved using rcurl options?

Could you try the original command after setting:

```
opts <- list(
  proxy         = "http://****",
  proxyusername = "****", 
  proxypassword = "*****", 
  proxyport     = ****
)

options(RCurlOptions = opts)
```

**Comment by sjgmr13** [comment]
It does not work.

**Comment by jhuovari** [comment]
What about?

```
httr::set_config(httr::use_proxy(url = "XXX", port = XXX), override = TRUE)
t1 <- get_eurostat("tsdtr420", filters = list(geo = c("UK")))
httr::reset_config()
```

**Comment by sjgmr13** [comment]
Gives the following error message:

```
Error in open.connection(con, "rb") : 
  Timeout was reached: Connection timed out after 10000 milliseconds
```

**Comment by jhuovari** [comment]
Too bad. I would like to solve this rather with setting options for httr/curl than with argument to `get_eurostat_json`.

**Comment by jhuovari** [comment]
Should work now with:

```
t1 <- get_eurostat_json("tsdtr420", 
            filters = list(geo = c("UK", "FR", "PL", "ES", "PT")), 
            config = httr::use_proxy(url, port, username, password))
```

**Comment by engandersonbrasil** [comment]
thank's for your help!
